// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20201120110454_s3")]
    partial class s3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBorn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("028d9dca-77ec-4874-a421-2ffabbe3b93a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 139, DateTimeKind.Local).AddTicks(3102),
                            DateOfBorn = new DateTime(1998, 3, 20, 6, 52, 35, 652, DateTimeKind.Unspecified).AddTicks(7730),
                            Email = "Jackson.Wilson@etsy.co",
                            Name = "Ethan",
                            Surname = "Abbott",
                            Title = "qq.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 144, DateTimeKind.Local).AddTicks(7888)
                        },
                        new
                        {
                            Id = new Guid("2884e0c1-f440-4ba4-9473-3864f52208e1"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 144, DateTimeKind.Local).AddTicks(9100),
                            DateOfBorn = new DateTime(1974, 4, 13, 12, 29, 55, 45, DateTimeKind.Unspecified).AddTicks(2964),
                            Email = "Brandon.Swift@etsy.biz",
                            Name = "Addison",
                            Surname = "Whitehouse",
                            Title = "yahoo.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3497)
                        },
                        new
                        {
                            Id = new Guid("d5b88846-fbb2-412b-8286-4b3ccd9907e4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3511),
                            DateOfBorn = new DateTime(1980, 8, 28, 1, 12, 1, 332, DateTimeKind.Unspecified).AddTicks(9893),
                            Email = "Carter.Riddick@wordpress.biz",
                            Name = "Colton",
                            Surname = "Wright",
                            Title = "qq.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3586)
                        },
                        new
                        {
                            Id = new Guid("3c9abafe-b947-4831-86cc-7ff6dcef1475"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3588),
                            DateOfBorn = new DateTime(2016, 2, 4, 20, 42, 21, 251, DateTimeKind.Unspecified).AddTicks(438),
                            Email = "A.Abbott@maplin.net",
                            Name = "Dominic",
                            Surname = "Bradshaw",
                            Title = "linkedin.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3767)
                        },
                        new
                        {
                            Id = new Guid("c6a6a356-02a7-4075-b658-0579dc3cb432"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3769),
                            DateOfBorn = new DateTime(1996, 9, 17, 4, 29, 22, 856, DateTimeKind.Unspecified).AddTicks(947),
                            Email = "T.Rossi@theguardian.biz",
                            Name = "Samuel",
                            Surname = "Silva",
                            Title = "amazon.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3798)
                        },
                        new
                        {
                            Id = new Guid("626decf8-0e85-4412-8913-5f4bb66ca07b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3803),
                            DateOfBorn = new DateTime(1995, 4, 13, 14, 51, 0, 576, DateTimeKind.Unspecified).AddTicks(2055),
                            Email = "Connor.Whitehead@theguardian.us",
                            Name = "Bella",
                            Surname = "Thompson",
                            Title = "globo.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3892)
                        },
                        new
                        {
                            Id = new Guid("8d14a00d-a30e-4406-bc38-bf448366d466"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3893),
                            DateOfBorn = new DateTime(1979, 6, 15, 11, 29, 52, 855, DateTimeKind.Unspecified).AddTicks(2687),
                            Email = "M.Wilson@linkedin.com",
                            Name = "Ashley",
                            Surname = "Leach",
                            Title = "youtube.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3916)
                        },
                        new
                        {
                            Id = new Guid("55c5f133-e9c7-4a6c-b24b-92140ff3712f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3917),
                            DateOfBorn = new DateTime(2013, 3, 24, 12, 54, 24, 86, DateTimeKind.Unspecified).AddTicks(8372),
                            Email = "C.Lindsay@wordpress.org",
                            Name = "Brandon",
                            Surname = "Giles",
                            Title = "techcrunch.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3978)
                        },
                        new
                        {
                            Id = new Guid("136f348b-2947-4919-8cd3-46970ec57091"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(3980),
                            DateOfBorn = new DateTime(2017, 11, 25, 23, 57, 20, 469, DateTimeKind.Unspecified).AddTicks(8624),
                            Email = "M.Mellor@taobao.com",
                            Name = "Nevaeh",
                            Surname = "Hooper",
                            Title = "techcrunch.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4014)
                        },
                        new
                        {
                            Id = new Guid("408da1c5-0533-4088-bece-5bf68c08145f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4017),
                            DateOfBorn = new DateTime(1994, 12, 2, 1, 14, 52, 986, DateTimeKind.Unspecified).AddTicks(7001),
                            Email = "J.Evans@msdn.co",
                            Name = "Zoey",
                            Surname = "Johnson",
                            Title = "lego.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4078)
                        },
                        new
                        {
                            Id = new Guid("e8bceae4-c773-4f9f-b438-3ae54b6af3b4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4079),
                            DateOfBorn = new DateTime(1982, 9, 12, 11, 27, 30, 603, DateTimeKind.Unspecified).AddTicks(9566),
                            Email = "N.Thorne@stackoverflow.org",
                            Name = "Jocelyn",
                            Surname = "Walker",
                            Title = "youtube.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4101)
                        },
                        new
                        {
                            Id = new Guid("7ab92bcb-c793-4c31-81d7-19cc3331b418"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4102),
                            DateOfBorn = new DateTime(2006, 4, 15, 3, 30, 8, 154, DateTimeKind.Unspecified).AddTicks(7006),
                            Email = "D.Schofield@bing.co",
                            Name = "Christian",
                            Surname = "Whittaker",
                            Title = "qq.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4177)
                        },
                        new
                        {
                            Id = new Guid("005a8817-e949-4786-8c0b-8b0447f89365"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4179),
                            DateOfBorn = new DateTime(1981, 10, 5, 11, 57, 43, 698, DateTimeKind.Unspecified).AddTicks(5778),
                            Email = "Peyton.Cullen@theguardian.org.uk",
                            Name = "Nathan",
                            Surname = "Barlow",
                            Title = "live.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4200)
                        },
                        new
                        {
                            Id = new Guid("ad369514-9dd5-4277-8b88-6bedffea66e4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4202),
                            DateOfBorn = new DateTime(2000, 3, 30, 17, 52, 45, 604, DateTimeKind.Unspecified).AddTicks(1865),
                            Email = "A.Mcfarlane@taobao.us",
                            Name = "Tyler",
                            Surname = "Coles",
                            Title = "theguardian.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4260)
                        },
                        new
                        {
                            Id = new Guid("106c9153-bb27-4912-9544-20cafcd38663"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4261),
                            DateOfBorn = new DateTime(2008, 10, 6, 2, 21, 2, 307, DateTimeKind.Unspecified).AddTicks(3696),
                            Email = "Easton.Abbott@youtube.co.uk",
                            Name = "Lucas",
                            Surname = "Lewis",
                            Title = "live.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4281)
                        },
                        new
                        {
                            Id = new Guid("a14b127b-609c-4017-9ed6-62bf78a6dcfe"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4283),
                            DateOfBorn = new DateTime(2019, 11, 14, 16, 38, 48, 503, DateTimeKind.Unspecified).AddTicks(7006),
                            Email = "Robert.Hancock@adamriddick.net",
                            Name = "Julia",
                            Surname = "Perkins",
                            Title = "stackoverflow.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4341)
                        },
                        new
                        {
                            Id = new Guid("e31b57b0-5b5a-4329-a9ba-4219f92d7814"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4342),
                            DateOfBorn = new DateTime(1993, 9, 29, 5, 30, 51, 416, DateTimeKind.Unspecified).AddTicks(546),
                            Email = "Violet.Naylor@baidu.co.uk",
                            Name = "Arianna",
                            Surname = "Cullen",
                            Title = "sohu.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4366)
                        },
                        new
                        {
                            Id = new Guid("690ee062-4624-4ac3-adbc-12631be3a7bd"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4404),
                            DateOfBorn = new DateTime(1997, 7, 21, 23, 34, 41, 304, DateTimeKind.Unspecified).AddTicks(4559),
                            Email = "Makayla.Johnson@bing.org",
                            Name = "Bryson",
                            Surname = "Chadwick",
                            Title = "techcrunch.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4428)
                        },
                        new
                        {
                            Id = new Guid("041795c2-b5aa-468d-88e5-2afc914d046a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4429),
                            DateOfBorn = new DateTime(1979, 5, 15, 13, 52, 31, 265, DateTimeKind.Unspecified).AddTicks(5674),
                            Email = "S.Shepherd@youtube.biz",
                            Name = "Ariana",
                            Surname = "Johnson",
                            Title = "ebay.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4486)
                        },
                        new
                        {
                            Id = new Guid("074a03c9-9bbb-46b2-a28a-26723d56935b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4487),
                            DateOfBorn = new DateTime(2019, 10, 18, 10, 2, 18, 96, DateTimeKind.Unspecified).AddTicks(8106),
                            Email = "B.Thomas@qq.info",
                            Name = "Carter",
                            Surname = "Vaughan",
                            Title = "gmail.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4510)
                        },
                        new
                        {
                            Id = new Guid("36f04478-459d-4d22-af3a-7b8ed64a7a19"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4512),
                            DateOfBorn = new DateTime(1997, 4, 18, 23, 58, 1, 500, DateTimeKind.Unspecified).AddTicks(9022),
                            Email = "Ariana.Blair@arstechnica.net",
                            Name = "Isaiah",
                            Surname = "Whitehead",
                            Title = "lego.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4589)
                        },
                        new
                        {
                            Id = new Guid("b7eed2c7-0c3b-4b64-8bc2-f930f590e0c3"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4590),
                            DateOfBorn = new DateTime(1979, 4, 20, 4, 16, 3, 872, DateTimeKind.Unspecified).AddTicks(1817),
                            Email = "S.Leach@ebay.net",
                            Name = "Madison",
                            Surname = "Jackson",
                            Title = "yahoo.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4613)
                        },
                        new
                        {
                            Id = new Guid("6eabfcab-e102-46ac-8702-a928c13907dc"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4614),
                            DateOfBorn = new DateTime(2010, 5, 25, 21, 32, 49, 613, DateTimeKind.Unspecified).AddTicks(5068),
                            Email = "A.Cullen@wikipedia.net",
                            Name = "Joshua",
                            Surname = "Vaughan",
                            Title = "arstechnica.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4728)
                        },
                        new
                        {
                            Id = new Guid("5d32c0f6-7d33-47ff-9c6e-a2052cd7487b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4729),
                            DateOfBorn = new DateTime(1988, 6, 20, 5, 50, 27, 136, DateTimeKind.Unspecified).AddTicks(8714),
                            Email = "H.Hooper@youtube.co.uk",
                            Name = "Jeremiah",
                            Surname = "Briggs",
                            Title = "techcrunch.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4753)
                        },
                        new
                        {
                            Id = new Guid("ffec24e8-5816-4c9a-ae8f-c9fc59b37e50"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4754),
                            DateOfBorn = new DateTime(1972, 12, 29, 15, 49, 31, 130, DateTimeKind.Unspecified).AddTicks(8248),
                            Email = "Lucy.Weaver@linkedin.info",
                            Name = "Thomas",
                            Surname = "Barlow",
                            Title = "ebay.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4814)
                        },
                        new
                        {
                            Id = new Guid("d86bb142-7265-4510-8481-b1c39abb083d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4816),
                            DateOfBorn = new DateTime(1999, 3, 9, 23, 8, 14, 9, DateTimeKind.Unspecified).AddTicks(1682),
                            Email = "M.Obrien@wikipedia.org",
                            Name = "Genesis",
                            Surname = "Kenny",
                            Title = "maplin.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4838)
                        },
                        new
                        {
                            Id = new Guid("8680ded4-e8f9-4dab-b673-b8b16007b970"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4839),
                            DateOfBorn = new DateTime(2011, 1, 13, 6, 6, 29, 783, DateTimeKind.Unspecified).AddTicks(5316),
                            Email = "Nathaniel.Swift@etsy.info",
                            Name = "Piper",
                            Surname = "Green",
                            Title = "linkedin.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4898)
                        },
                        new
                        {
                            Id = new Guid("e78f39db-c22a-466e-9113-89fae294d6c9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4899),
                            DateOfBorn = new DateTime(1980, 4, 20, 18, 8, 17, 664, DateTimeKind.Unspecified).AddTicks(7099),
                            Email = "Nathan.Mcgrath@globo.biz",
                            Name = "Jaxon",
                            Surname = "Carroll",
                            Title = "linkedin.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4920)
                        },
                        new
                        {
                            Id = new Guid("81271e9f-2808-4902-a5fc-cc56e737f95b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4921),
                            DateOfBorn = new DateTime(2014, 3, 24, 13, 7, 37, 386, DateTimeKind.Unspecified).AddTicks(4896),
                            Email = "Bailey.Mcgrath@live.co",
                            Name = "Levi",
                            Surname = "Rossi",
                            Title = "paypal.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4980)
                        },
                        new
                        {
                            Id = new Guid("a7ee76cd-dac7-4542-8102-51a8060a3ae7"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(4982),
                            DateOfBorn = new DateTime(2009, 5, 19, 10, 55, 21, 852, DateTimeKind.Unspecified).AddTicks(686),
                            Email = "T.Dale@taobao.co.uk",
                            Name = "Jeremiah",
                            Surname = "Naylor",
                            Title = "taobao.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5003)
                        },
                        new
                        {
                            Id = new Guid("cfd7087e-d120-4d50-aa45-68809240403e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5004),
                            DateOfBorn = new DateTime(2018, 12, 18, 14, 37, 26, 229, DateTimeKind.Unspecified).AddTicks(5344),
                            Email = "A.Watson@amazon.co.uk",
                            Name = "Mason",
                            Surname = "Briggs",
                            Title = "google.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5062)
                        },
                        new
                        {
                            Id = new Guid("ec0eff40-e682-44dc-b3c2-cf56c577b33e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5064),
                            DateOfBorn = new DateTime(1986, 3, 11, 0, 49, 15, 964, DateTimeKind.Unspecified).AddTicks(3811),
                            Email = "Kayla.Akhtar@msdn.co.uk",
                            Name = "Elizabeth",
                            Surname = "Lord",
                            Title = "theguardian.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5123)
                        },
                        new
                        {
                            Id = new Guid("c8764b68-ef26-472b-a73c-9ebabf0d5c4a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5125),
                            DateOfBorn = new DateTime(1981, 2, 9, 13, 17, 15, 796, DateTimeKind.Unspecified).AddTicks(3708),
                            Email = "A.Whittaker@arstechnica.biz",
                            Name = "Brody",
                            Surname = "Mellor",
                            Title = "wordpress.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5151)
                        },
                        new
                        {
                            Id = new Guid("bb4ef872-fd7d-419d-b581-ce64c207e184"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5155),
                            DateOfBorn = new DateTime(2004, 7, 2, 18, 55, 43, 856, DateTimeKind.Unspecified).AddTicks(8136),
                            Email = "C.Wright@etsy.info",
                            Name = "Hunter",
                            Surname = "Obrien",
                            Title = "paypal.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5214)
                        },
                        new
                        {
                            Id = new Guid("4c480504-54cb-4cfc-9cee-91feda42dafc"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5216),
                            DateOfBorn = new DateTime(1993, 8, 19, 16, 55, 31, 768, DateTimeKind.Unspecified).AddTicks(85),
                            Email = "Olivia.Lewis@sky.info",
                            Name = "Maya",
                            Surname = "Silva",
                            Title = "sohu.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5237)
                        },
                        new
                        {
                            Id = new Guid("4213868f-1278-4988-8013-b4725506b389"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5238),
                            DateOfBorn = new DateTime(1988, 7, 1, 15, 13, 5, 188, DateTimeKind.Unspecified).AddTicks(4948),
                            Email = "M.Taylor@theguardian.us",
                            Name = "Zoe",
                            Surname = "Vaughan",
                            Title = "live.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5312)
                        },
                        new
                        {
                            Id = new Guid("4c1409a6-24e8-4a02-9872-1559d9776641"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5313),
                            DateOfBorn = new DateTime(1997, 5, 21, 8, 33, 11, 408, DateTimeKind.Unspecified).AddTicks(545),
                            Email = "Isaac.Akhtar@paypal.net",
                            Name = "Brooklyn",
                            Surname = "Walters",
                            Title = "ask.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5336)
                        },
                        new
                        {
                            Id = new Guid("dea74ad2-8eb8-42d6-8d1a-05660c561963"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5337),
                            DateOfBorn = new DateTime(1990, 6, 3, 23, 1, 5, 363, DateTimeKind.Unspecified).AddTicks(6932),
                            Email = "B.Mcfarlane@qq.net",
                            Name = "Alex",
                            Surname = "Adam",
                            Title = "wikipedia.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5397)
                        },
                        new
                        {
                            Id = new Guid("a4bfd389-bc4b-4605-af64-4bb143c85d8a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5398),
                            DateOfBorn = new DateTime(2017, 4, 7, 1, 51, 29, 432, DateTimeKind.Unspecified).AddTicks(5832),
                            Email = "Dylan.Burrows@ask.us",
                            Name = "Reagan",
                            Surname = "Little",
                            Title = "paypal.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5420)
                        },
                        new
                        {
                            Id = new Guid("4444625a-0839-4027-9643-6feb6bddf53e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5422),
                            DateOfBorn = new DateTime(2013, 6, 2, 14, 31, 37, 661, DateTimeKind.Unspecified).AddTicks(2234),
                            Email = "Robert.Osborne@techcrunch.org.uk",
                            Name = "Autumn",
                            Surname = "Haines",
                            Title = "sky.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5481)
                        },
                        new
                        {
                            Id = new Guid("c1690ac4-3e2f-4284-a98d-db6d65213ed0"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5482),
                            DateOfBorn = new DateTime(1976, 4, 24, 21, 54, 54, 344, DateTimeKind.Unspecified).AddTicks(4780),
                            Email = "Aaliyah.Lewis@msdn.us",
                            Name = "Caleb",
                            Surname = "Hancock",
                            Title = "bestbuy.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5507)
                        },
                        new
                        {
                            Id = new Guid("55b6e919-d9d7-4d9c-918d-67bc7bda33d6"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5508),
                            DateOfBorn = new DateTime(2020, 2, 10, 20, 28, 12, 836, DateTimeKind.Unspecified).AddTicks(9370),
                            Email = "Alexandra.Whittaker@cnn.net",
                            Name = "Zoe",
                            Surname = "Johnson",
                            Title = "paypal.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5567)
                        },
                        new
                        {
                            Id = new Guid("28cb88a6-a654-4aee-908d-e32aa68b3a1e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5568),
                            DateOfBorn = new DateTime(1978, 3, 17, 14, 40, 22, 618, DateTimeKind.Unspecified).AddTicks(3512),
                            Email = "A.Nelson@live.biz",
                            Name = "Kevin",
                            Surname = "Giles",
                            Title = "paypal.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5591)
                        },
                        new
                        {
                            Id = new Guid("3f65bf37-e256-4978-bd63-3f536bce962f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5592),
                            DateOfBorn = new DateTime(1995, 12, 8, 3, 32, 43, 685, DateTimeKind.Unspecified).AddTicks(3891),
                            Email = "Samuel.Nash@bing.net",
                            Name = "Gabriel",
                            Surname = "Whittaker",
                            Title = "deviantart.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5650)
                        },
                        new
                        {
                            Id = new Guid("d8b2fd13-68a1-4daa-91ea-aa52bc37ee7a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5652),
                            DateOfBorn = new DateTime(2002, 10, 9, 13, 4, 13, 204, DateTimeKind.Unspecified).AddTicks(984),
                            Email = "Morgan.Taylor@techcrunch.net",
                            Name = "Grace",
                            Surname = "Osborne",
                            Title = "techcrunch.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5673)
                        },
                        new
                        {
                            Id = new Guid("536be5a5-7837-465f-bdc6-eaacc0dcb8c4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5674),
                            DateOfBorn = new DateTime(1996, 8, 22, 19, 15, 37, 599, DateTimeKind.Unspecified).AddTicks(3883),
                            Email = "J.Mac@google.biz",
                            Name = "Kayla",
                            Surname = "Vaughan",
                            Title = "techcrunch.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5735)
                        },
                        new
                        {
                            Id = new Guid("132e9bab-84b7-459e-8f8a-e8d24f27d016"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5736),
                            DateOfBorn = new DateTime(2009, 8, 25, 7, 23, 30, 520, DateTimeKind.Unspecified).AddTicks(7828),
                            Email = "L.Wood@gmail.us",
                            Name = "Gavin",
                            Surname = "Harris",
                            Title = "expedia.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5827)
                        },
                        new
                        {
                            Id = new Guid("aef36166-d325-4962-8060-edb0102d914b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5828),
                            DateOfBorn = new DateTime(1977, 4, 26, 10, 45, 8, 843, DateTimeKind.Unspecified).AddTicks(1756),
                            Email = "L.Barlow@163.biz",
                            Name = "Brandon",
                            Surname = "Peters",
                            Title = "taobao.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5852)
                        },
                        new
                        {
                            Id = new Guid("33edfff2-ac21-4ee1-b600-500b5b7e2794"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5853),
                            DateOfBorn = new DateTime(2006, 6, 14, 18, 49, 22, 636, DateTimeKind.Unspecified).AddTicks(8362),
                            Email = "Paul.Mcfarlane@expedia.org",
                            Name = "Sarah",
                            Surname = "Rossi",
                            Title = "yelp.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5917)
                        },
                        new
                        {
                            Id = new Guid("d7988583-e30e-41f9-8b40-92882f3c8d49"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5918),
                            DateOfBorn = new DateTime(2003, 4, 16, 15, 59, 18, 191, DateTimeKind.Unspecified).AddTicks(9080),
                            Email = "Bailey.Fleming@baidu.org",
                            Name = "Justin",
                            Surname = "Obrien",
                            Title = "sohu.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("30cc4887-ccfe-4ec6-963e-399f6a1f7468"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(5941),
                            DateOfBorn = new DateTime(1972, 12, 14, 20, 23, 13, 959, DateTimeKind.Unspecified).AddTicks(8127),
                            Email = "Blake.Hancock@msdn.biz",
                            Name = "Autumn",
                            Surname = "Power",
                            Title = "qq.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6019)
                        },
                        new
                        {
                            Id = new Guid("9216637a-3566-4c4a-8cde-ee5b49104754"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6020),
                            DateOfBorn = new DateTime(2008, 10, 18, 22, 16, 40, 96, DateTimeKind.Unspecified).AddTicks(8650),
                            Email = "Taylor.Smith@gmail.net",
                            Name = "Lily",
                            Surname = "Sanders",
                            Title = "google.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6042)
                        },
                        new
                        {
                            Id = new Guid("5da31c27-2609-43f0-b01e-4c86cf044230"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6043),
                            DateOfBorn = new DateTime(2016, 9, 25, 23, 34, 28, 551, DateTimeKind.Unspecified).AddTicks(1676),
                            Email = "Tristan.Evans@bbc.info",
                            Name = "Sydney",
                            Surname = "Walters",
                            Title = "sky.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6103)
                        },
                        new
                        {
                            Id = new Guid("ab06d112-52b8-4618-8841-3eb2b2eb3c50"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6104),
                            DateOfBorn = new DateTime(1977, 12, 18, 5, 36, 34, 438, DateTimeKind.Unspecified).AddTicks(9761),
                            Email = "Z.Seymour@live.org.uk",
                            Name = "Alexander",
                            Surname = "Joyce",
                            Title = "taobao.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6126)
                        },
                        new
                        {
                            Id = new Guid("37945355-f60f-4e26-ae6a-59ce684a42d1"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6127),
                            DateOfBorn = new DateTime(2004, 12, 23, 2, 17, 42, 48, DateTimeKind.Unspecified).AddTicks(1058),
                            Email = "London.Jennings@amazon.org",
                            Name = "Nathaniel",
                            Surname = "Wilson",
                            Title = "microsoft.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6186)
                        },
                        new
                        {
                            Id = new Guid("d943ffe6-378c-41a0-be56-0059b7f6fce5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6188),
                            DateOfBorn = new DateTime(2002, 11, 2, 21, 37, 12, 814, DateTimeKind.Unspecified).AddTicks(7702),
                            Email = "A.Roberts@amazon.co",
                            Name = "Carter",
                            Surname = "Mann",
                            Title = "arstechnica.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6210)
                        },
                        new
                        {
                            Id = new Guid("b474b9bf-f00d-4a91-a481-9db37c514d5a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6211),
                            DateOfBorn = new DateTime(2017, 1, 31, 12, 25, 4, 789, DateTimeKind.Unspecified).AddTicks(3732),
                            Email = "D.Mohamed@qq.co",
                            Name = "Nolan",
                            Surname = "Abbott",
                            Title = "microsoft.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6273)
                        },
                        new
                        {
                            Id = new Guid("ef2d7b26-0397-44c3-998e-796c1c476f89"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6275),
                            DateOfBorn = new DateTime(1985, 3, 19, 23, 4, 35, 707, DateTimeKind.Unspecified).AddTicks(2193),
                            Email = "G.Thorne@google.info",
                            Name = "Natalie",
                            Surname = "Seymour",
                            Title = "amazon.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6296)
                        },
                        new
                        {
                            Id = new Guid("4a543451-0bfa-409a-b5da-f6d9ff5a4c0d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6297),
                            DateOfBorn = new DateTime(1980, 3, 7, 16, 37, 25, 166, DateTimeKind.Unspecified).AddTicks(8488),
                            Email = "S.Osborne@gmail.biz",
                            Name = "Grayson",
                            Surname = "Robinson",
                            Title = "bing.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6357)
                        },
                        new
                        {
                            Id = new Guid("1290eb66-b095-48f5-b13d-6b7b45c4b89d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6359),
                            DateOfBorn = new DateTime(1998, 6, 21, 1, 25, 48, 254, DateTimeKind.Unspecified).AddTicks(7036),
                            Email = "William.Welch@stackoverflow.co",
                            Name = "Elizabeth",
                            Surname = "Thomas",
                            Title = "youtube.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6380)
                        },
                        new
                        {
                            Id = new Guid("66024425-2fbe-4a66-a998-eb2911490423"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6381),
                            DateOfBorn = new DateTime(2018, 2, 27, 23, 10, 31, 439, DateTimeKind.Unspecified).AddTicks(3422),
                            Email = "Christian.Cassidy@bing.net",
                            Name = "Carson",
                            Surname = "Stuart",
                            Title = "ask.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6509)
                        },
                        new
                        {
                            Id = new Guid("f227f51e-96f3-4003-9a79-445376f98391"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6511),
                            DateOfBorn = new DateTime(2012, 12, 3, 18, 49, 53, 507, DateTimeKind.Unspecified).AddTicks(1500),
                            Email = "Jacob.Osborne@bbc.us",
                            Name = "Adam",
                            Surname = "Naylor",
                            Title = "theguardian.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6573)
                        },
                        new
                        {
                            Id = new Guid("8dc95de1-1f3f-491d-bc90-bdea0ced7d91"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6575),
                            DateOfBorn = new DateTime(1980, 1, 20, 21, 55, 43, 807, DateTimeKind.Unspecified).AddTicks(7358),
                            Email = "J.Wright@microsoft.biz",
                            Name = "Paul",
                            Surname = "Mohamed",
                            Title = "studio1337.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6598)
                        },
                        new
                        {
                            Id = new Guid("89b60529-143f-4fdb-9887-5e180448985a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6599),
                            DateOfBorn = new DateTime(1977, 1, 17, 20, 17, 13, 912, DateTimeKind.Unspecified).AddTicks(3886),
                            Email = "L.Jones@microsoft.org.uk",
                            Name = "Jace",
                            Surname = "Sanders",
                            Title = "lego.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6660)
                        },
                        new
                        {
                            Id = new Guid("bff943ab-29f3-4a05-9ee6-6c4c52d34cf3"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6661),
                            DateOfBorn = new DateTime(1975, 2, 28, 4, 12, 6, 980, DateTimeKind.Unspecified).AddTicks(6409),
                            Email = "J.Roberts@microsoft.com",
                            Name = "Joshua",
                            Surname = "Hilton",
                            Title = "ebay.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6686)
                        },
                        new
                        {
                            Id = new Guid("d556d8de-2a24-4d92-9a52-b760c85e019d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6689),
                            DateOfBorn = new DateTime(2020, 4, 8, 16, 52, 59, 758, DateTimeKind.Unspecified).AddTicks(3166),
                            Email = "Annabelle.Perkins@msdn.com",
                            Name = "Mackenzie",
                            Surname = "Leach",
                            Title = "flipkart.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            Id = new Guid("caec2ccd-d8dd-4142-b0e8-2b4d0da94c07"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6766),
                            DateOfBorn = new DateTime(1977, 7, 22, 21, 31, 4, 955, DateTimeKind.Unspecified).AddTicks(4230),
                            Email = "B.Shepherd@163.biz",
                            Name = "Luis",
                            Surname = "Whelan",
                            Title = "theguardian.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6788)
                        },
                        new
                        {
                            Id = new Guid("5f9c155c-0a63-4765-a8bc-e089ef4c4f42"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6789),
                            DateOfBorn = new DateTime(1975, 7, 27, 15, 22, 20, 470, DateTimeKind.Unspecified).AddTicks(2330),
                            Email = "S.Hancock@deviantart.org.uk",
                            Name = "Austin",
                            Surname = "Jones",
                            Title = "bet365.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6848)
                        },
                        new
                        {
                            Id = new Guid("99e2dba7-3f75-4b31-9361-d29e4342cfce"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6850),
                            DateOfBorn = new DateTime(1987, 1, 15, 13, 12, 14, 213, DateTimeKind.Unspecified).AddTicks(9394),
                            Email = "P.Joyce@expedia.com",
                            Name = "Michael",
                            Surname = "Brown",
                            Title = "wikia.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6871)
                        },
                        new
                        {
                            Id = new Guid("ddb629ca-0213-44d2-88c1-b5f073743aa6"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6872),
                            DateOfBorn = new DateTime(1984, 10, 19, 13, 53, 21, 694, DateTimeKind.Unspecified).AddTicks(9677),
                            Email = "V.Bradshaw@ebay.com",
                            Name = "Zoey",
                            Surname = "Akhtar",
                            Title = "techcrunch.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6932)
                        },
                        new
                        {
                            Id = new Guid("2832a5f5-27d4-4ca5-8143-ff612831c8cf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6933),
                            DateOfBorn = new DateTime(2019, 6, 2, 3, 24, 15, 69, DateTimeKind.Unspecified).AddTicks(7752),
                            Email = "Carlos.Cassidy@adamriddick.net",
                            Name = "Melanie",
                            Surname = "Savage",
                            Title = "cnn.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(6954)
                        },
                        new
                        {
                            Id = new Guid("17a311ed-1f07-402a-b09b-035b77e48ffe"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7022),
                            DateOfBorn = new DateTime(2004, 12, 23, 15, 50, 20, 215, DateTimeKind.Unspecified).AddTicks(7768),
                            Email = "Carter.Brown@yahoo.info",
                            Name = "Sydney",
                            Surname = "Giles",
                            Title = "youtube.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = new Guid("0264086b-4118-4072-ac33-f38922ad646b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7049),
                            DateOfBorn = new DateTime(1982, 9, 21, 17, 56, 37, 692, DateTimeKind.Unspecified).AddTicks(7360),
                            Email = "T.Wyatt@live.co.uk",
                            Name = "Brianna",
                            Surname = "Savage",
                            Title = "techcrunch.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7114)
                        },
                        new
                        {
                            Id = new Guid("3e05faeb-a36b-4cb4-aa7d-eec30e968db0"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7115),
                            DateOfBorn = new DateTime(2017, 8, 5, 20, 17, 12, 852, DateTimeKind.Unspecified).AddTicks(1340),
                            Email = "S.Shepherd@sky.biz",
                            Name = "Kimberly",
                            Surname = "Nelson",
                            Title = "yelp.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7137)
                        },
                        new
                        {
                            Id = new Guid("52fcff48-1f8e-4385-87a8-d90623bc06ac"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7138),
                            DateOfBorn = new DateTime(1976, 11, 2, 22, 55, 7, 116, DateTimeKind.Unspecified).AddTicks(1321),
                            Email = "Alexis.Coles@arstechnica.com",
                            Name = "Abigail",
                            Surname = "Barlow",
                            Title = "163.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7197)
                        },
                        new
                        {
                            Id = new Guid("d7c69591-a92f-437e-a762-f0c6afb20b3d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7198),
                            DateOfBorn = new DateTime(1994, 7, 24, 12, 26, 53, 716, DateTimeKind.Unspecified).AddTicks(6645),
                            Email = "Austin.Wyatt@microsoft.com",
                            Name = "Lillian",
                            Surname = "Lindsay",
                            Title = "arstechnica.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7220)
                        },
                        new
                        {
                            Id = new Guid("f8b6839a-1ac5-40d1-aec0-e7f89f1eb0cc"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7221),
                            DateOfBorn = new DateTime(1980, 8, 28, 7, 16, 2, 934, DateTimeKind.Unspecified).AddTicks(5711),
                            Email = "D.Haines@bestbuy.net",
                            Name = "Scarlett",
                            Surname = "Hilton",
                            Title = "pinterest.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7281)
                        },
                        new
                        {
                            Id = new Guid("b94d8e14-5d15-45d9-87e6-0a512aac9344"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7282),
                            DateOfBorn = new DateTime(1981, 9, 24, 10, 21, 55, 658, DateTimeKind.Unspecified).AddTicks(2138),
                            Email = "S.Giles@linkedin.us",
                            Name = "Ryder",
                            Surname = "Giles",
                            Title = "deviantart.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7305)
                        },
                        new
                        {
                            Id = new Guid("ae326508-5bff-4987-87c1-585419696ff5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7306),
                            DateOfBorn = new DateTime(1996, 3, 13, 0, 32, 12, 949, DateTimeKind.Unspecified).AddTicks(7000),
                            Email = "T.Mohamed@globo.net",
                            Name = "Chloe",
                            Surname = "White",
                            Title = "techcrunch.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7366)
                        },
                        new
                        {
                            Id = new Guid("14706abe-852a-4722-9845-dbc0f46cdf85"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7367),
                            DateOfBorn = new DateTime(1988, 3, 10, 23, 39, 45, 934, DateTimeKind.Unspecified).AddTicks(7596),
                            Email = "James.Sanders@gmail.org.uk",
                            Name = "Landon",
                            Surname = "Mohamed",
                            Title = "deviantart.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7388)
                        },
                        new
                        {
                            Id = new Guid("0cc6fc21-5d23-49aa-a7c0-d3f7ca54edea"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7390),
                            DateOfBorn = new DateTime(1987, 1, 22, 9, 25, 2, 928, DateTimeKind.Unspecified).AddTicks(9480),
                            Email = "Natalie.Thornton@qq.org.uk",
                            Name = "Logan",
                            Surname = "Watson",
                            Title = "studio1337.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7466)
                        },
                        new
                        {
                            Id = new Guid("dffd1b9b-5558-496d-8198-445779c59a53"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7468),
                            DateOfBorn = new DateTime(1994, 12, 17, 13, 21, 37, 563, DateTimeKind.Unspecified).AddTicks(827),
                            Email = "N.Mcfarlane@google.us",
                            Name = "Claire",
                            Surname = "Bradshaw",
                            Title = "expedia.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7490)
                        },
                        new
                        {
                            Id = new Guid("f2c5e850-39cf-4d94-b876-5773daf5f480"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7491),
                            DateOfBorn = new DateTime(2004, 6, 29, 10, 27, 19, 820, DateTimeKind.Unspecified).AddTicks(1230),
                            Email = "Audrey.Mohamed@etsy.org.uk",
                            Name = "Joseph",
                            Surname = "Stuart",
                            Title = "adamriddick.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7550)
                        },
                        new
                        {
                            Id = new Guid("7fba4893-9c1d-4251-a259-7a248fb8b9f4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7552),
                            DateOfBorn = new DateTime(1993, 9, 20, 11, 28, 44, 799, DateTimeKind.Unspecified).AddTicks(6158),
                            Email = "Samuel.Little@gmail.net",
                            Name = "Angel",
                            Surname = "Rossi",
                            Title = "bbc.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7572)
                        },
                        new
                        {
                            Id = new Guid("10b87668-5611-41d3-bebf-87e5c6f72682"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7573),
                            DateOfBorn = new DateTime(1981, 2, 8, 14, 42, 22, 249, DateTimeKind.Unspecified).AddTicks(2958),
                            Email = "Nathan.Burrows@bing.co.uk",
                            Name = "Brody",
                            Surname = "Thomas",
                            Title = "studio1337.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7632)
                        },
                        new
                        {
                            Id = new Guid("30b4feb0-a036-48ae-af45-2cbd870a5013"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7633),
                            DateOfBorn = new DateTime(1996, 4, 17, 22, 34, 29, 478, DateTimeKind.Unspecified).AddTicks(7997),
                            Email = "Christian.Barlow@arstechnica.co.uk",
                            Name = "Cooper",
                            Surname = "Whitehead",
                            Title = "youtube.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7653)
                        },
                        new
                        {
                            Id = new Guid("bc14a897-b706-45d3-8717-079653b22937"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7655),
                            DateOfBorn = new DateTime(1984, 7, 18, 11, 15, 35, 95, DateTimeKind.Unspecified).AddTicks(1179),
                            Email = "Layla.Sanders@yelp.org.uk",
                            Name = "Parker",
                            Surname = "Walker",
                            Title = "bbc.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7714)
                        },
                        new
                        {
                            Id = new Guid("3ecbeee8-b065-4327-af0e-a21d9bd9bcfd"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7715),
                            DateOfBorn = new DateTime(2009, 10, 8, 11, 4, 21, 538, DateTimeKind.Unspecified).AddTicks(1434),
                            Email = "Carson.Mohamed@taobao.org",
                            Name = "Kylie",
                            Surname = "Jones",
                            Title = "microsoft.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7775)
                        },
                        new
                        {
                            Id = new Guid("41f7a885-54e0-4675-bec2-ab0635f7c7b2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7776),
                            DateOfBorn = new DateTime(2019, 2, 20, 14, 14, 21, 38, DateTimeKind.Unspecified).AddTicks(5436),
                            Email = "J.Johnson@bing.info",
                            Name = "Jace",
                            Surname = "Boyd",
                            Title = "wordpress.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7801)
                        },
                        new
                        {
                            Id = new Guid("c927dc37-7eaa-4a9f-8f81-fb8846bd0283"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7802),
                            DateOfBorn = new DateTime(1972, 9, 24, 2, 3, 32, 374, DateTimeKind.Unspecified).AddTicks(4572),
                            Email = "Leah.Burrows@live.org.uk",
                            Name = "Avery",
                            Surname = "Leach",
                            Title = "bbc.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7860)
                        },
                        new
                        {
                            Id = new Guid("0b0a21b6-59d2-4301-95c8-f0aef5c68cf5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7862),
                            DateOfBorn = new DateTime(1973, 8, 22, 15, 51, 21, 214, DateTimeKind.Unspecified).AddTicks(4181),
                            Email = "Emily.Summers@youtube.info",
                            Name = "Lily",
                            Surname = "White",
                            Title = "baidu.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7883)
                        },
                        new
                        {
                            Id = new Guid("e23dd3d9-723c-42b3-920f-e9928441ef09"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7884),
                            DateOfBorn = new DateTime(2011, 8, 13, 0, 15, 3, 347, DateTimeKind.Unspecified).AddTicks(3958),
                            Email = "Ella.Mcgrath@baidu.info",
                            Name = "Bella",
                            Surname = "Thomas",
                            Title = "globo.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7944)
                        },
                        new
                        {
                            Id = new Guid("543ce89e-d8fd-47e1-a1fc-27cb4a92048b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7945),
                            DateOfBorn = new DateTime(1997, 4, 29, 22, 13, 8, 713, DateTimeKind.Unspecified).AddTicks(8824),
                            Email = "E.Whitehouse@bet365.biz",
                            Name = "Sophia",
                            Surname = "Joyce",
                            Title = "bet365.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7967)
                        },
                        new
                        {
                            Id = new Guid("eed7efa7-836f-4da1-af91-b118c10312ae"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(7968),
                            DateOfBorn = new DateTime(2019, 8, 21, 22, 36, 18, 211, DateTimeKind.Unspecified).AddTicks(7210),
                            Email = "Adrian.Jackson@theguardian.com",
                            Name = "Gavin",
                            Surname = "Seymour",
                            Title = "163.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8054)
                        },
                        new
                        {
                            Id = new Guid("6bbb84a0-668b-411d-b893-ee9db103837f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8056),
                            DateOfBorn = new DateTime(1984, 5, 29, 0, 46, 3, 447, DateTimeKind.Unspecified).AddTicks(7454),
                            Email = "N.Welch@maplin.org",
                            Name = "Samuel",
                            Surname = "Whitehead",
                            Title = "wikia.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8078)
                        },
                        new
                        {
                            Id = new Guid("24047256-0d68-4571-862a-075c1cebe90a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8079),
                            DateOfBorn = new DateTime(2015, 6, 22, 4, 49, 16, 879, DateTimeKind.Unspecified).AddTicks(1892),
                            Email = "N.Whelan@bbc.org",
                            Name = "Hannah",
                            Surname = "Silva",
                            Title = "bing.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8154)
                        },
                        new
                        {
                            Id = new Guid("e003ab4e-78ca-4a51-89c5-edde06bb08bf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8155),
                            DateOfBorn = new DateTime(1986, 4, 16, 20, 16, 39, 769, DateTimeKind.Unspecified).AddTicks(6392),
                            Email = "O.Briggs@google.info",
                            Name = "Kayla",
                            Surname = "Little",
                            Title = "amazon.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8180)
                        },
                        new
                        {
                            Id = new Guid("85b115a5-e119-4669-975e-098a5e6a5611"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8181),
                            DateOfBorn = new DateTime(1995, 9, 2, 14, 21, 1, 784, DateTimeKind.Unspecified).AddTicks(1231),
                            Email = "Caleb.Weaver@youtube.co",
                            Name = "Grace",
                            Surname = "Mohamed",
                            Title = "lego.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8238)
                        },
                        new
                        {
                            Id = new Guid("595b39a3-cfc6-44c4-adbf-c76732fe386d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8240),
                            DateOfBorn = new DateTime(1972, 3, 20, 19, 24, 18, 688, DateTimeKind.Unspecified).AddTicks(864),
                            Email = "Hunter.Silva@deviantart.com",
                            Name = "Dominic",
                            Surname = "Burrows",
                            Title = "paypal.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8260)
                        },
                        new
                        {
                            Id = new Guid("96ec76aa-ae07-4a7d-b63b-0cb6339fe93c"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8262),
                            DateOfBorn = new DateTime(1979, 7, 16, 21, 54, 21, 873, DateTimeKind.Unspecified).AddTicks(6468),
                            Email = "Bella.Swift@gmail.us",
                            Name = "Adrian",
                            Surname = "Burrows",
                            Title = "sohu.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 4, 54, 145, DateTimeKind.Local).AddTicks(8320)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
