// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20201120110637_s4")]
    partial class s4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBorn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff1cad7c-0551-4064-a745-a90e3b552ea9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 274, DateTimeKind.Local).AddTicks(813),
                            DateOfBorn = new DateTime(2020, 5, 25, 16, 25, 55, 484, DateTimeKind.Unspecified).AddTicks(776),
                            Email = "Scott.Mohamed@msdn.com",
                            Name = "Harper",
                            Surname = "Mann",
                            Title = "bing.org.uk"
                        },
                        new
                        {
                            Id = new Guid("69687d7a-3c9c-4a91-8287-57951c2525a4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(4455),
                            DateOfBorn = new DateTime(2007, 9, 18, 9, 57, 12, 495, DateTimeKind.Unspecified).AddTicks(6378),
                            Email = "M.Leach@studio1337.org",
                            Name = "Melanie",
                            Surname = "Whitehead",
                            Title = "paypal.co"
                        },
                        new
                        {
                            Id = new Guid("dc25c7f6-cc08-4fdd-9ac1-07131447ef8e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(4756),
                            DateOfBorn = new DateTime(1974, 3, 6, 8, 45, 4, 373, DateTimeKind.Unspecified).AddTicks(2003),
                            Email = "Ariana.Vaughan@etsy.info",
                            Name = "Sophie",
                            Surname = "Smith",
                            Title = "cnn.info"
                        },
                        new
                        {
                            Id = new Guid("62e5f2a8-8339-4d6f-9b8e-68e3b7308cec"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(4828),
                            DateOfBorn = new DateTime(2015, 7, 19, 15, 56, 4, 233, DateTimeKind.Unspecified).AddTicks(1008),
                            Email = "Chloe.Cassidy@globo.biz",
                            Name = "Ellie",
                            Surname = "Giles",
                            Title = "expedia.biz"
                        },
                        new
                        {
                            Id = new Guid("0fbc8a68-465a-414d-ab96-a62001ed7ca1"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(4850),
                            DateOfBorn = new DateTime(1981, 2, 13, 23, 36, 0, 820, DateTimeKind.Unspecified).AddTicks(7948),
                            Email = "Cameron.Mellor@youtube.org",
                            Name = "Nicholas",
                            Surname = "Hancock",
                            Title = "yelp.biz"
                        },
                        new
                        {
                            Id = new Guid("31d65cb6-9d8c-4bc5-a846-2c945679dcaf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(4979),
                            DateOfBorn = new DateTime(1978, 2, 25, 15, 13, 5, 115, DateTimeKind.Unspecified).AddTicks(2872),
                            Email = "Molly.Haines@globo.org.uk",
                            Name = "Evan",
                            Surname = "Smith",
                            Title = "ask.biz"
                        },
                        new
                        {
                            Id = new Guid("7aa71bb7-620b-465c-95fd-793d6d868ccf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5014),
                            DateOfBorn = new DateTime(1994, 6, 25, 19, 54, 14, 182, DateTimeKind.Unspecified).AddTicks(4628),
                            Email = "C.Bradshaw@microsoft.org.uk",
                            Name = "Gavin",
                            Surname = "Welch",
                            Title = "adamriddick.co.uk"
                        },
                        new
                        {
                            Id = new Guid("3868ccb7-421f-42bb-a600-01df28e5ab80"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5100),
                            DateOfBorn = new DateTime(1991, 4, 18, 5, 15, 22, 556, DateTimeKind.Unspecified).AddTicks(8598),
                            Email = "A.Lindsay@studio1337.co",
                            Name = "Carter",
                            Surname = "Wood",
                            Title = "taobao.org"
                        },
                        new
                        {
                            Id = new Guid("45c9dd13-6f0f-4767-af4b-69a5d70c2f7f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5125),
                            DateOfBorn = new DateTime(1996, 10, 12, 1, 14, 36, 949, DateTimeKind.Unspecified).AddTicks(4690),
                            Email = "S.Williams@msdn.com",
                            Name = "Ellie",
                            Surname = "Naylor",
                            Title = "studio1337.us"
                        },
                        new
                        {
                            Id = new Guid("78d73c4f-5aa5-480d-8e99-8805400d049b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5182),
                            DateOfBorn = new DateTime(1977, 5, 27, 16, 42, 49, 787, DateTimeKind.Unspecified).AddTicks(4048),
                            Email = "J.Sanders@wikipedia.biz",
                            Name = "Avery",
                            Surname = "Silva",
                            Title = "bestbuy.com"
                        },
                        new
                        {
                            Id = new Guid("ca77aab2-1a6a-4e21-a272-b02399bce555"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5205),
                            DateOfBorn = new DateTime(1983, 2, 10, 11, 11, 18, 117, DateTimeKind.Unspecified).AddTicks(9882),
                            Email = "Autumn.Wilson@wikipedia.net",
                            Name = "Adrian",
                            Surname = "Cassidy",
                            Title = "bestbuy.info"
                        },
                        new
                        {
                            Id = new Guid("ae32981a-9efe-46f3-b4c6-20d19321b188"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5259),
                            DateOfBorn = new DateTime(1974, 4, 5, 15, 25, 28, 810, DateTimeKind.Unspecified).AddTicks(9803),
                            Email = "Ayden.Summers@sohu.net",
                            Name = "Violet",
                            Surname = "Hancock",
                            Title = "bbc.info"
                        },
                        new
                        {
                            Id = new Guid("59701db9-06dc-477a-acdb-d460db495ee4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5280),
                            DateOfBorn = new DateTime(1984, 11, 2, 17, 38, 41, 826, DateTimeKind.Unspecified).AddTicks(2437),
                            Email = "Emily.Evans@microsoft.org",
                            Name = "Nathan",
                            Surname = "Kenny",
                            Title = "theguardian.biz"
                        },
                        new
                        {
                            Id = new Guid("af7a9f60-872b-4fb5-961b-90bf7e13ceaf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5334),
                            DateOfBorn = new DateTime(1994, 8, 30, 5, 30, 54, 754, DateTimeKind.Unspecified).AddTicks(8268),
                            Email = "Madison.White@gmail.org.uk",
                            Name = "Brianna",
                            Surname = "Mclean",
                            Title = "sohu.co.uk"
                        },
                        new
                        {
                            Id = new Guid("1fe0de5c-7877-41b3-ae45-50b6b4b9780a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5393),
                            DateOfBorn = new DateTime(2008, 6, 12, 6, 25, 10, 482, DateTimeKind.Unspecified).AddTicks(5604),
                            Email = "Colton.Lindsay@theguardian.org.uk",
                            Name = "Sebastian",
                            Surname = "Bradshaw",
                            Title = "theguardian.us"
                        },
                        new
                        {
                            Id = new Guid("eb596175-8ef6-45ca-a074-5d4072baff6a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5416),
                            DateOfBorn = new DateTime(2012, 2, 4, 9, 29, 34, 79, DateTimeKind.Unspecified).AddTicks(9836),
                            Email = "N.Welch@ebay.org",
                            Name = "Gabriel",
                            Surname = "Power",
                            Title = "yahoo.org.uk"
                        },
                        new
                        {
                            Id = new Guid("b0d10eb7-ccd5-492f-9fac-45b2d2b4ae9b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5471),
                            DateOfBorn = new DateTime(1991, 2, 21, 2, 40, 31, 868, DateTimeKind.Unspecified).AddTicks(259),
                            Email = "G.Rossi@lego.net",
                            Name = "Hunter",
                            Surname = "Harris",
                            Title = "ebay.org"
                        },
                        new
                        {
                            Id = new Guid("42b6f098-cf78-4cd1-b82c-27a3e0446759"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5494),
                            DateOfBorn = new DateTime(1994, 4, 23, 8, 6, 35, 717, DateTimeKind.Unspecified).AddTicks(3685),
                            Email = "M.Whittaker@paypal.net",
                            Name = "Alyssa",
                            Surname = "Peters",
                            Title = "baidu.org"
                        },
                        new
                        {
                            Id = new Guid("d6aaa2b9-7cc3-47f3-bb60-342357bf88d9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5549),
                            DateOfBorn = new DateTime(2019, 2, 15, 6, 32, 5, 840, DateTimeKind.Unspecified).AddTicks(9888),
                            Email = "Ethan.Johnson@wordpress.biz",
                            Name = "Paul",
                            Surname = "Riddick",
                            Title = "linkedin.co"
                        },
                        new
                        {
                            Id = new Guid("078c84e8-ee43-4494-a251-34866022869e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5571),
                            DateOfBorn = new DateTime(2019, 1, 13, 8, 8, 59, 427, DateTimeKind.Unspecified).AddTicks(346),
                            Email = "Mackenzie.Briggs@ask.net",
                            Name = "Daniel",
                            Surname = "Mcfarlane",
                            Title = "globo.co.uk"
                        },
                        new
                        {
                            Id = new Guid("348910b7-3acd-4cd4-ae00-d69a26787dae"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5624),
                            DateOfBorn = new DateTime(1991, 12, 18, 6, 6, 25, 607, DateTimeKind.Unspecified).AddTicks(1396),
                            Email = "A.Silva@deviantart.org.uk",
                            Name = "Makayla",
                            Surname = "Whittaker",
                            Title = "adamriddick.com"
                        },
                        new
                        {
                            Id = new Guid("56d9d82e-c401-4ce0-8656-3383c0320c23"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5646),
                            DateOfBorn = new DateTime(2020, 9, 3, 15, 47, 10, 679, DateTimeKind.Unspecified).AddTicks(7726),
                            Email = "Kylie.Coles@amazon.info",
                            Name = "Kimberly",
                            Surname = "Haines",
                            Title = "adamriddick.co"
                        },
                        new
                        {
                            Id = new Guid("736d0ee4-dc5d-41e1-8aba-cd6768458516"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5717),
                            DateOfBorn = new DateTime(2015, 7, 2, 22, 12, 13, 577, DateTimeKind.Unspecified).AddTicks(4316),
                            Email = "J.Thornton@stackoverflow.co",
                            Name = "Juan",
                            Surname = "Briggs",
                            Title = "wikipedia.info"
                        },
                        new
                        {
                            Id = new Guid("5630325c-ff4f-43c1-b33f-1e50ee90e992"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5740),
                            DateOfBorn = new DateTime(1993, 3, 30, 22, 27, 42, 483, DateTimeKind.Unspecified).AddTicks(6117),
                            Email = "V.Boyd@techcrunch.co",
                            Name = "Leah",
                            Surname = "Naylor",
                            Title = "studio1337.net"
                        },
                        new
                        {
                            Id = new Guid("d08dd748-cc7d-4eba-8dc7-a6f0727483e2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5798),
                            DateOfBorn = new DateTime(1973, 6, 8, 14, 25, 0, 233, DateTimeKind.Unspecified).AddTicks(6870),
                            Email = "L.Mcgregor@wikia.com",
                            Name = "Mark",
                            Surname = "Bradshaw",
                            Title = "pinterest.org.uk"
                        },
                        new
                        {
                            Id = new Guid("562de8d3-5d64-4407-a7f3-293555868f1f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5820),
                            DateOfBorn = new DateTime(1999, 6, 18, 11, 50, 43, 898, DateTimeKind.Unspecified).AddTicks(1616),
                            Email = "N.Briggs@adamriddick.com",
                            Name = "Hudson",
                            Surname = "Lewis",
                            Title = "yelp.net"
                        },
                        new
                        {
                            Id = new Guid("3a0a0b47-d737-4e37-bc2b-7fb3767756ee"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5874),
                            DateOfBorn = new DateTime(2002, 2, 16, 15, 41, 22, 846, DateTimeKind.Unspecified).AddTicks(9008),
                            Email = "Charlotte.Roberts@google.com",
                            Name = "Aaron",
                            Surname = "Mohamed",
                            Title = "amazon.org"
                        },
                        new
                        {
                            Id = new Guid("254b1ede-d357-44a6-8a60-44eb0db929a2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5896),
                            DateOfBorn = new DateTime(2005, 11, 15, 17, 54, 33, 321, DateTimeKind.Unspecified).AddTicks(7372),
                            Email = "Stella.Silva@163.co",
                            Name = "Gabriel",
                            Surname = "Vaughan",
                            Title = "ask.co.uk"
                        },
                        new
                        {
                            Id = new Guid("fda4bd73-8590-4e46-94dd-c4b9a8712c57"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(5978),
                            DateOfBorn = new DateTime(2002, 8, 26, 12, 28, 2, 481, DateTimeKind.Unspecified).AddTicks(1132),
                            Email = "N.Nash@lego.co",
                            Name = "Joshua",
                            Surname = "Thornton",
                            Title = "bet365.net"
                        },
                        new
                        {
                            Id = new Guid("a699e843-6627-4c0f-ae6b-20181313b9fd"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6036),
                            DateOfBorn = new DateTime(2014, 2, 26, 15, 9, 29, 66, DateTimeKind.Unspecified).AddTicks(9454),
                            Email = "K.Mellor@bestbuy.org",
                            Name = "Lucy",
                            Surname = "Dale",
                            Title = "bbc.us"
                        },
                        new
                        {
                            Id = new Guid("b1559795-67f5-4133-b584-ac98358a9c79"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6061),
                            DateOfBorn = new DateTime(2005, 4, 9, 17, 54, 2, 235, DateTimeKind.Unspecified).AddTicks(4256),
                            Email = "Colton.Johnson@flipkart.com",
                            Name = "Tyler",
                            Surname = "Lindsay",
                            Title = "sky.biz"
                        },
                        new
                        {
                            Id = new Guid("4a2f59ea-70b3-42d8-af74-1fd824a9d71c"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6114),
                            DateOfBorn = new DateTime(2018, 8, 11, 17, 26, 43, 254, DateTimeKind.Unspecified).AddTicks(7034),
                            Email = "T.Seymour@google.com",
                            Name = "Bella",
                            Surname = "Smith",
                            Title = "ask.biz"
                        },
                        new
                        {
                            Id = new Guid("15249789-cdb2-4e68-a509-73d16c63c595"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6136),
                            DateOfBorn = new DateTime(2010, 5, 18, 3, 46, 52, 770, DateTimeKind.Unspecified).AddTicks(9314),
                            Email = "Aubree.Baldwin@adamriddick.org.uk",
                            Name = "Autumn",
                            Surname = "Thorne",
                            Title = "youtube.org.uk"
                        },
                        new
                        {
                            Id = new Guid("35035803-9179-4928-8118-07f4c49cd3a4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6191),
                            DateOfBorn = new DateTime(2017, 3, 11, 23, 17, 47, 187, DateTimeKind.Unspecified).AddTicks(5452),
                            Email = "D.Osborne@studio1337.org",
                            Name = "Victoria",
                            Surname = "Davies",
                            Title = "gmail.co"
                        },
                        new
                        {
                            Id = new Guid("fe50342f-efda-4676-bb75-64ee6fa83db5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6214),
                            DateOfBorn = new DateTime(2018, 9, 17, 19, 48, 47, 819, DateTimeKind.Unspecified).AddTicks(6298),
                            Email = "William.Thomas@bet365.org",
                            Name = "Hailey",
                            Surname = "Naylor",
                            Title = "techcrunch.com"
                        },
                        new
                        {
                            Id = new Guid("50f907d6-f3f7-4f01-a68b-3e08109bcf0a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6267),
                            DateOfBorn = new DateTime(1993, 11, 30, 23, 3, 45, 473, DateTimeKind.Unspecified).AddTicks(7078),
                            Email = "K.Dale@yelp.co",
                            Name = "Lily",
                            Surname = "Williams",
                            Title = "etsy.net"
                        },
                        new
                        {
                            Id = new Guid("993e3f44-3ec3-4a0f-85e8-f5ec1c84dbb7"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6288),
                            DateOfBorn = new DateTime(1983, 2, 24, 4, 12, 27, 916, DateTimeKind.Unspecified).AddTicks(9362),
                            Email = "T.Thomas@globo.net",
                            Name = "Jace",
                            Surname = "Summers",
                            Title = "live.com"
                        },
                        new
                        {
                            Id = new Guid("0a31a1aa-0787-4bf1-a3ac-dc6f412884fa"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6361),
                            DateOfBorn = new DateTime(1988, 10, 8, 3, 24, 40, 289, DateTimeKind.Unspecified).AddTicks(1920),
                            Email = "A.Mac@yahoo.org",
                            Name = "Liam",
                            Surname = "Riddick",
                            Title = "linkedin.us"
                        },
                        new
                        {
                            Id = new Guid("c3dfd105-d8bd-4e0c-bb29-8dc6fc7d34aa"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6385),
                            DateOfBorn = new DateTime(2009, 12, 1, 22, 49, 20, 8, DateTimeKind.Unspecified).AddTicks(8522),
                            Email = "Alex.Silva@bestbuy.biz",
                            Name = "Xavier",
                            Surname = "Taylor",
                            Title = "bet365.net"
                        },
                        new
                        {
                            Id = new Guid("94f9e07a-34ce-4f13-a0e2-74a1a287f4d6"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6441),
                            DateOfBorn = new DateTime(1985, 11, 26, 7, 47, 42, 43, DateTimeKind.Unspecified).AddTicks(8454),
                            Email = "Mackenzie.Green@163.co",
                            Name = "Faith",
                            Surname = "Williams",
                            Title = "gmail.us"
                        },
                        new
                        {
                            Id = new Guid("02015827-1b73-4bc8-92d5-e629bbe48c27"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6462),
                            DateOfBorn = new DateTime(1995, 8, 18, 21, 59, 33, 84, DateTimeKind.Unspecified).AddTicks(6822),
                            Email = "Madeline.Fleming@stackoverflow.org.uk",
                            Name = "Anthony",
                            Surname = "Buckley",
                            Title = "pinterest.net"
                        },
                        new
                        {
                            Id = new Guid("b738246f-ba6c-4873-8dee-76c1ef953e1b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6517),
                            DateOfBorn = new DateTime(1988, 8, 13, 18, 58, 21, 36, DateTimeKind.Unspecified).AddTicks(6014),
                            Email = "S.Carroll@taobao.com",
                            Name = "Bailey",
                            Surname = "Little",
                            Title = "adamriddick.com"
                        },
                        new
                        {
                            Id = new Guid("c81251ad-a92f-493e-a7eb-bb941958964a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6570),
                            DateOfBorn = new DateTime(2011, 5, 5, 6, 49, 36, 557, DateTimeKind.Unspecified).AddTicks(3622),
                            Email = "S.Shepherd@flipkart.org.uk",
                            Name = "Jonathan",
                            Surname = "Vaughan",
                            Title = "amazon.com"
                        },
                        new
                        {
                            Id = new Guid("792b47a5-747c-48d5-8d04-e5b6fa592771"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6592),
                            DateOfBorn = new DateTime(1987, 1, 27, 8, 33, 22, 280, DateTimeKind.Unspecified).AddTicks(2973),
                            Email = "Alexander.Perkins@wordpress.us",
                            Name = "Scott",
                            Surname = "Hooper",
                            Title = "maplin.org"
                        },
                        new
                        {
                            Id = new Guid("04f30ce7-315a-44a5-af6f-41832ee0cbaa"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6646),
                            DateOfBorn = new DateTime(1993, 9, 12, 23, 11, 31, 659, DateTimeKind.Unspecified).AddTicks(6111),
                            Email = "Khloe.Swift@globo.info",
                            Name = "Kylie",
                            Surname = "Rossi",
                            Title = "sohu.com"
                        },
                        new
                        {
                            Id = new Guid("6e0a5f6c-c550-4ab2-a0f4-6acfcf901fb7"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6667),
                            DateOfBorn = new DateTime(1996, 5, 25, 18, 26, 13, 711, DateTimeKind.Unspecified).AddTicks(7429),
                            Email = "Justin.Cullen@studio1337.us",
                            Name = "Paul",
                            Surname = "Savage",
                            Title = "sohu.org"
                        },
                        new
                        {
                            Id = new Guid("3461633c-83ca-41ed-8031-bd19e88bc08e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6727),
                            DateOfBorn = new DateTime(1995, 3, 28, 21, 13, 11, 678, DateTimeKind.Unspecified).AddTicks(1081),
                            Email = "E.Mohamed@amazon.co",
                            Name = "Samuel",
                            Surname = "Cassidy",
                            Title = "bet365.co.uk"
                        },
                        new
                        {
                            Id = new Guid("7765d8f8-20f9-4520-abe6-e512d0594007"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6748),
                            DateOfBorn = new DateTime(1979, 4, 15, 9, 57, 30, 193, DateTimeKind.Unspecified).AddTicks(4769),
                            Email = "Alexander.Kenny@taobao.co.uk",
                            Name = "Joseph",
                            Surname = "Sinclair",
                            Title = "wikipedia.net"
                        },
                        new
                        {
                            Id = new Guid("9bb98c9b-0e48-4505-bfd0-f059a013ce34"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6803),
                            DateOfBorn = new DateTime(1998, 9, 22, 20, 13, 17, 684, DateTimeKind.Unspecified).AddTicks(1326),
                            Email = "K.Stuart@wikia.org.uk",
                            Name = "Ariana",
                            Surname = "Wright",
                            Title = "maplin.co"
                        },
                        new
                        {
                            Id = new Guid("b6e6f818-b779-4b98-a9a7-55bb8a3c1f55"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6825),
                            DateOfBorn = new DateTime(2000, 9, 6, 15, 0, 47, 921, DateTimeKind.Unspecified).AddTicks(3018),
                            Email = "L.Johnson@163.com",
                            Name = "Naomi",
                            Surname = "Bradshaw",
                            Title = "ask.us"
                        },
                        new
                        {
                            Id = new Guid("c17dce77-b715-4340-9a28-766115b21a82"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6879),
                            DateOfBorn = new DateTime(2000, 8, 12, 13, 51, 33, 646, DateTimeKind.Unspecified).AddTicks(9094),
                            Email = "E.Watson@bet365.org",
                            Name = "Alexis",
                            Surname = "Giles",
                            Title = "microsoft.co"
                        },
                        new
                        {
                            Id = new Guid("92585aa7-002a-4e28-8f22-88f5ff178e34"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6900),
                            DateOfBorn = new DateTime(2016, 5, 4, 11, 25, 57, 80, DateTimeKind.Unspecified).AddTicks(6646),
                            Email = "Bella.Fleming@maplin.co",
                            Name = "Ellie",
                            Surname = "Walters",
                            Title = "microsoft.us"
                        },
                        new
                        {
                            Id = new Guid("7d6b30d8-074f-4059-be75-c8cf3d2b8107"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(6994),
                            DateOfBorn = new DateTime(2013, 2, 13, 19, 55, 44, 868, DateTimeKind.Unspecified).AddTicks(3706),
                            Email = "J.Shepherd@bet365.biz",
                            Name = "Stella",
                            Surname = "Shepherd",
                            Title = "sohu.net"
                        },
                        new
                        {
                            Id = new Guid("cbf49021-f309-4370-a139-52f69e965e89"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7017),
                            DateOfBorn = new DateTime(1975, 11, 14, 15, 45, 7, 0, DateTimeKind.Unspecified).AddTicks(3265),
                            Email = "L.Wyatt@paypal.com",
                            Name = "Faith",
                            Surname = "Taylor",
                            Title = "bbc.biz"
                        },
                        new
                        {
                            Id = new Guid("004f723b-3a07-439b-8c96-48fd495db96a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7075),
                            DateOfBorn = new DateTime(1986, 1, 16, 20, 33, 8, 970, DateTimeKind.Unspecified).AddTicks(1884),
                            Email = "H.Mohamed@qq.com",
                            Name = "Jacob",
                            Surname = "Seymour",
                            Title = "wordpress.biz"
                        },
                        new
                        {
                            Id = new Guid("5001b741-f43e-4d54-a5df-397c02a843d2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7097),
                            DateOfBorn = new DateTime(2000, 6, 3, 20, 20, 20, 600, DateTimeKind.Unspecified).AddTicks(3119),
                            Email = "H.Jennings@stackoverflow.biz",
                            Name = "Natalie",
                            Surname = "Perkins",
                            Title = "linkedin.org"
                        },
                        new
                        {
                            Id = new Guid("a5407e8d-29cb-42b1-962b-a6cd7ae87707"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7152),
                            DateOfBorn = new DateTime(1976, 6, 13, 0, 35, 3, 597, DateTimeKind.Unspecified).AddTicks(8109),
                            Email = "Isaac.Silva@theguardian.org",
                            Name = "Andrea",
                            Surname = "Brown",
                            Title = "bet365.biz"
                        },
                        new
                        {
                            Id = new Guid("4331e8f6-d856-499d-9a0e-e1c594717c23"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7206),
                            DateOfBorn = new DateTime(2007, 10, 22, 22, 43, 11, 726, DateTimeKind.Unspecified).AddTicks(5682),
                            Email = "B.Nelson@ask.biz",
                            Name = "Luke",
                            Surname = "Lewis",
                            Title = "expedia.biz"
                        },
                        new
                        {
                            Id = new Guid("fd58b360-a34f-40fa-83ae-8c0977018a28"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7228),
                            DateOfBorn = new DateTime(1977, 3, 12, 14, 31, 17, 465, DateTimeKind.Unspecified).AddTicks(5032),
                            Email = "Nathaniel.Cassidy@expedia.biz",
                            Name = "Bentley",
                            Surname = "Obrien",
                            Title = "youtube.co.uk"
                        },
                        new
                        {
                            Id = new Guid("da5a4792-eb6d-4044-a0b4-9de7eb1a595d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7280),
                            DateOfBorn = new DateTime(2003, 12, 21, 6, 8, 57, 124, DateTimeKind.Unspecified).AddTicks(2620),
                            Email = "J.Mohamed@sohu.biz",
                            Name = "Samuel",
                            Surname = "Obrien",
                            Title = "techcrunch.com"
                        },
                        new
                        {
                            Id = new Guid("c498cd7f-ac00-4ef2-ba01-d97485aaf927"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7301),
                            DateOfBorn = new DateTime(1973, 6, 5, 21, 36, 24, 37, DateTimeKind.Unspecified).AddTicks(9625),
                            Email = "Nevaeh.Whitehouse@techcrunch.org.uk",
                            Name = "Maya",
                            Surname = "Mcgregor",
                            Title = "ebay.net"
                        },
                        new
                        {
                            Id = new Guid("0d5dec9e-53c8-4d1c-90a6-58b3e9b23fed"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7354),
                            DateOfBorn = new DateTime(2007, 11, 4, 3, 6, 15, 659, DateTimeKind.Unspecified).AddTicks(1792),
                            Email = "Elizabeth.Briggs@gmail.org.uk",
                            Name = "Mason",
                            Surname = "Harris",
                            Title = "wikipedia.co"
                        },
                        new
                        {
                            Id = new Guid("7cbec04f-35f1-4c71-9a31-82fe84fa7878"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7378),
                            DateOfBorn = new DateTime(1975, 11, 15, 1, 35, 46, 261, DateTimeKind.Unspecified).AddTicks(9968),
                            Email = "M.Wright@pinterest.info",
                            Name = "Kennedy",
                            Surname = "Peters",
                            Title = "globo.org.uk"
                        },
                        new
                        {
                            Id = new Guid("fcd4e507-e14a-4945-8f83-43d7be67508b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7434),
                            DateOfBorn = new DateTime(1988, 1, 21, 16, 14, 39, 720, DateTimeKind.Unspecified).AddTicks(4659),
                            Email = "Tristan.Power@linkedin.net",
                            Name = "Gavin",
                            Surname = "Akhtar",
                            Title = "google.info"
                        },
                        new
                        {
                            Id = new Guid("28aec933-b40f-4bf2-8e4d-7847d33443e9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7454),
                            DateOfBorn = new DateTime(2002, 7, 27, 8, 26, 58, 863, DateTimeKind.Unspecified).AddTicks(5186),
                            Email = "Dominic.Fleming@expedia.co.uk",
                            Name = "Jack",
                            Surname = "Burrows",
                            Title = "qq.us"
                        },
                        new
                        {
                            Id = new Guid("00eb6dac-6778-4d02-bb2c-f093f845cca2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7510),
                            DateOfBorn = new DateTime(2015, 10, 1, 4, 13, 8, 436, DateTimeKind.Unspecified).AddTicks(3746),
                            Email = "Anna.Summers@gmail.net",
                            Name = "Jayden",
                            Surname = "Boyd",
                            Title = "adamriddick.org"
                        },
                        new
                        {
                            Id = new Guid("e77101ec-7a1f-4b25-bdb9-e9964018c640"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7532),
                            DateOfBorn = new DateTime(1997, 10, 18, 10, 31, 5, 264, DateTimeKind.Unspecified).AddTicks(1363),
                            Email = "Scarlett.Cassidy@gmail.org",
                            Name = "Brooklyn",
                            Surname = "Evans",
                            Title = "ebay.co.uk"
                        },
                        new
                        {
                            Id = new Guid("9cd224ff-f837-4d13-b18c-d2f7715c38cf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7599),
                            DateOfBorn = new DateTime(2010, 10, 28, 16, 19, 6, 548, DateTimeKind.Unspecified).AddTicks(7536),
                            Email = "J.Akhtar@163.org",
                            Name = "Jasmine",
                            Surname = "Nash",
                            Title = "yahoo.com"
                        },
                        new
                        {
                            Id = new Guid("e813b5db-c1c1-4c5c-bd74-d92244bb65df"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7652),
                            DateOfBorn = new DateTime(1982, 7, 29, 18, 44, 19, 76, DateTimeKind.Unspecified).AddTicks(9452),
                            Email = "N.Vaughan@bbc.info",
                            Name = "Madeline",
                            Surname = "Whittaker",
                            Title = "msdn.biz"
                        },
                        new
                        {
                            Id = new Guid("c4bf8fa0-20d2-4e1e-a138-5d25742bdbe2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7675),
                            DateOfBorn = new DateTime(1998, 9, 9, 23, 11, 19, 737, DateTimeKind.Unspecified).AddTicks(8083),
                            Email = "Lillian.Riddick@theguardian.net",
                            Name = "Natalie",
                            Surname = "Smith",
                            Title = "bing.co.uk"
                        },
                        new
                        {
                            Id = new Guid("c1ef18d3-44e2-4b46-891b-74d767078bf9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7768),
                            DateOfBorn = new DateTime(1974, 6, 25, 15, 40, 46, 571, DateTimeKind.Unspecified).AddTicks(565),
                            Email = "A.Mann@gmail.us",
                            Name = "Anthony",
                            Surname = "Robinson",
                            Title = "yahoo.com"
                        },
                        new
                        {
                            Id = new Guid("0dbafc0b-2844-43dc-8e82-0b5c7fdd2f2c"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7792),
                            DateOfBorn = new DateTime(1972, 6, 14, 17, 48, 42, 765, DateTimeKind.Unspecified).AddTicks(4624),
                            Email = "R.Leach@deviantart.co.uk",
                            Name = "Alexandra",
                            Surname = "Thompson",
                            Title = "live.biz"
                        },
                        new
                        {
                            Id = new Guid("1832ee06-3a14-460a-bd58-106f8ff7789c"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7848),
                            DateOfBorn = new DateTime(2010, 4, 11, 10, 53, 22, 689, DateTimeKind.Unspecified).AddTicks(3180),
                            Email = "Kennedy.Watson@qq.us",
                            Name = "Zoe",
                            Surname = "Summers",
                            Title = "live.info"
                        },
                        new
                        {
                            Id = new Guid("56089bd1-9f6b-49a6-90d9-87bbaeebd5e4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7869),
                            DateOfBorn = new DateTime(2007, 2, 14, 19, 8, 10, 492, DateTimeKind.Unspecified).AddTicks(6194),
                            Email = "Annabelle.Evans@amazon.net",
                            Name = "Abigail",
                            Surname = "Rossi",
                            Title = "microsoft.co.uk"
                        },
                        new
                        {
                            Id = new Guid("d89fec1d-e458-44ab-9557-fa44233627f8"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7920),
                            DateOfBorn = new DateTime(1988, 3, 29, 13, 4, 25, 459, DateTimeKind.Unspecified).AddTicks(1223),
                            Email = "Kayla.Sanders@etsy.net",
                            Name = "Lillian",
                            Surname = "Stuart",
                            Title = "sohu.biz"
                        },
                        new
                        {
                            Id = new Guid("ad20351b-7be0-4203-821b-f862a983c9bd"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(7942),
                            DateOfBorn = new DateTime(1984, 4, 4, 4, 46, 32, 769, DateTimeKind.Unspecified).AddTicks(2),
                            Email = "O.Swift@bbc.co",
                            Name = "Dylan",
                            Surname = "Williams",
                            Title = "theguardian.org"
                        },
                        new
                        {
                            Id = new Guid("0f8fe72e-031b-4907-a105-ced5ffa06fce"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8025),
                            DateOfBorn = new DateTime(1982, 10, 17, 17, 5, 41, 598, DateTimeKind.Unspecified).AddTicks(8942),
                            Email = "A.Cassidy@theguardian.org",
                            Name = "Naomi",
                            Surname = "White",
                            Title = "google.co"
                        },
                        new
                        {
                            Id = new Guid("a2b7595a-4875-4d3d-a7a8-9d33bcc847a9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8047),
                            DateOfBorn = new DateTime(2018, 10, 10, 18, 19, 37, 773, DateTimeKind.Unspecified).AddTicks(3262),
                            Email = "J.Stuart@baidu.biz",
                            Name = "Levi",
                            Surname = "Carroll",
                            Title = "techcrunch.org"
                        },
                        new
                        {
                            Id = new Guid("a2e3de74-4357-4627-aa7d-5be4f7c647c4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8105),
                            DateOfBorn = new DateTime(2009, 12, 30, 0, 22, 7, 94, DateTimeKind.Unspecified).AddTicks(6320),
                            Email = "A.Coles@linkedin.com",
                            Name = "Noah",
                            Surname = "Fleming",
                            Title = "theguardian.biz"
                        },
                        new
                        {
                            Id = new Guid("c3b26f39-abd5-42db-9b52-738381035276"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8127),
                            DateOfBorn = new DateTime(2012, 6, 6, 5, 12, 38, 52, DateTimeKind.Unspecified).AddTicks(354),
                            Email = "C.Whitehouse@microsoft.biz",
                            Name = "Brayden",
                            Surname = "Mellor",
                            Title = "theguardian.biz"
                        },
                        new
                        {
                            Id = new Guid("40b168ac-487c-41c0-8460-715028575db6"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8182),
                            DateOfBorn = new DateTime(1986, 9, 24, 14, 52, 15, 226, DateTimeKind.Unspecified).AddTicks(1162),
                            Email = "Katherine.Peters@deviantart.com",
                            Name = "Jackson",
                            Surname = "Abbott",
                            Title = "youtube.biz"
                        },
                        new
                        {
                            Id = new Guid("bb1aa006-ac96-4014-8291-60284a3e08b9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8203),
                            DateOfBorn = new DateTime(2017, 6, 22, 15, 2, 21, 130, DateTimeKind.Unspecified).AddTicks(6868),
                            Email = "Aria.Weaver@gmail.us",
                            Name = "Jayden",
                            Surname = "Osborne",
                            Title = "sohu.us"
                        },
                        new
                        {
                            Id = new Guid("e8386560-f44e-4cd4-be61-a1679fdca924"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8273),
                            DateOfBorn = new DateTime(1977, 1, 16, 1, 34, 13, 870, DateTimeKind.Unspecified).AddTicks(9372),
                            Email = "Joshua.Briggs@wikipedia.co.uk",
                            Name = "Addison",
                            Surname = "Carroll",
                            Title = "msdn.co"
                        },
                        new
                        {
                            Id = new Guid("e48116b2-3631-42f8-a924-1373be24be9d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8294),
                            DateOfBorn = new DateTime(2007, 9, 30, 20, 28, 56, 780, DateTimeKind.Unspecified).AddTicks(9810),
                            Email = "L.Taylor@live.info",
                            Name = "Ayden",
                            Surname = "Burrows",
                            Title = "bing.com"
                        },
                        new
                        {
                            Id = new Guid("9b483eb9-8505-4381-b4dd-a4efeb643b06"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8349),
                            DateOfBorn = new DateTime(2004, 5, 22, 2, 47, 25, 510, DateTimeKind.Unspecified).AddTicks(6994),
                            Email = "Hudson.Joyce@amazon.org",
                            Name = "Joshua",
                            Surname = "Harris",
                            Title = "youtube.biz"
                        },
                        new
                        {
                            Id = new Guid("cabcc834-d456-4397-866e-64e860ca5124"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8402),
                            DateOfBorn = new DateTime(1993, 9, 11, 21, 53, 13, 740, DateTimeKind.Unspecified).AddTicks(4539),
                            Email = "A.Cassidy@pinterest.info",
                            Name = "Jaxon",
                            Surname = "Thompson",
                            Title = "yelp.us"
                        },
                        new
                        {
                            Id = new Guid("5e63cab1-565a-44fe-8712-f4418a55879f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8427),
                            DateOfBorn = new DateTime(1975, 6, 19, 8, 27, 32, 521, DateTimeKind.Unspecified).AddTicks(3833),
                            Email = "T.Robinson@linkedin.biz",
                            Name = "Michael",
                            Surname = "Osborne",
                            Title = "baidu.net"
                        },
                        new
                        {
                            Id = new Guid("2a83b7f4-9e7f-424f-8db4-b771b9db4d20"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8481),
                            DateOfBorn = new DateTime(2008, 7, 23, 10, 20, 34, 258, DateTimeKind.Unspecified).AddTicks(5134),
                            Email = "Melanie.Mcfarlane@studio1337.info",
                            Name = "Wyatt",
                            Surname = "Davies",
                            Title = "msdn.com"
                        },
                        new
                        {
                            Id = new Guid("ca2854e2-bde3-4e1d-96d8-e40384358e08"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8503),
                            DateOfBorn = new DateTime(1991, 8, 14, 20, 12, 42, 922, DateTimeKind.Unspecified).AddTicks(3135),
                            Email = "D.Osborne@studio1337.com",
                            Name = "Scarlett",
                            Surname = "Wright",
                            Title = "wikia.us"
                        },
                        new
                        {
                            Id = new Guid("db329fbe-be81-4488-a682-2f9fcf95fb80"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8558),
                            DateOfBorn = new DateTime(2002, 8, 19, 14, 51, 59, 225, DateTimeKind.Unspecified).AddTicks(6170),
                            Email = "Sophia.Briggs@sohu.biz",
                            Name = "Bryson",
                            Surname = "Hilton",
                            Title = "pinterest.us"
                        },
                        new
                        {
                            Id = new Guid("44689f72-fc2a-46d8-9e47-957c311a379b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8580),
                            DateOfBorn = new DateTime(1999, 8, 21, 21, 8, 32, 820, DateTimeKind.Unspecified).AddTicks(6633),
                            Email = "D.Watson@google.co",
                            Name = "Ariana",
                            Surname = "Bradshaw",
                            Title = "pinterest.net"
                        },
                        new
                        {
                            Id = new Guid("67749749-8dc0-4e9e-bb42-ae4b0cce62e9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8632),
                            DateOfBorn = new DateTime(1999, 3, 18, 7, 16, 30, 191, DateTimeKind.Unspecified).AddTicks(419),
                            Email = "J.Cullen@sohu.us",
                            Name = "Isabella",
                            Surname = "Stuart",
                            Title = "expedia.co.uk"
                        },
                        new
                        {
                            Id = new Guid("afd7e074-f1a1-492a-a5a8-0e9a82793211"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8655),
                            DateOfBorn = new DateTime(2016, 3, 4, 12, 59, 20, 887, DateTimeKind.Unspecified).AddTicks(7596),
                            Email = "Aiden.Kenny@microsoft.info",
                            Name = "Camila",
                            Surname = "Mohamed",
                            Title = "msdn.com"
                        },
                        new
                        {
                            Id = new Guid("d77a2fbb-56de-418a-b6f9-8c2ce0b7cc03"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8708),
                            DateOfBorn = new DateTime(1981, 6, 3, 3, 50, 45, 672, DateTimeKind.Unspecified).AddTicks(9875),
                            Email = "W.Fleming@flipkart.net",
                            Name = "Grayson",
                            Surname = "Sanders",
                            Title = "sky.org.uk"
                        },
                        new
                        {
                            Id = new Guid("dd439673-0625-4174-b28d-2e843230be2b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(8731),
                            DateOfBorn = new DateTime(2015, 2, 19, 16, 7, 57, 74, DateTimeKind.Unspecified).AddTicks(1918),
                            Email = "Joseph.Rossi@adamriddick.net",
                            Name = "Madison",
                            Surname = "Whitehouse",
                            Title = "google.org"
                        },
                        new
                        {
                            Id = new Guid("d1bdeb46-e44f-412a-9c28-7873f3a7e42f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(9106),
                            DateOfBorn = new DateTime(2007, 11, 1, 14, 18, 11, 215, DateTimeKind.Unspecified).AddTicks(4566),
                            Email = "Zoe.Carroll@bestbuy.net",
                            Name = "Jocelyn",
                            Surname = "Fleming",
                            Title = "pinterest.co"
                        },
                        new
                        {
                            Id = new Guid("cbb16818-6180-4a24-bfca-55bd100568c9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(9137),
                            DateOfBorn = new DateTime(2018, 10, 18, 16, 0, 38, 585, DateTimeKind.Unspecified).AddTicks(9058),
                            Email = "Gabriella.Jones@wikipedia.info",
                            Name = "Camila",
                            Surname = "Coles",
                            Title = "techcrunch.co"
                        },
                        new
                        {
                            Id = new Guid("410088bb-4931-494b-af84-7234a4563944"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(9216),
                            DateOfBorn = new DateTime(2000, 2, 11, 10, 36, 11, 321, DateTimeKind.Unspecified).AddTicks(8688),
                            Email = "Ayden.Thomas@studio1337.biz",
                            Name = "Juan",
                            Surname = "Abbott",
                            Title = "youtube.info"
                        },
                        new
                        {
                            Id = new Guid("db4eee8a-1de2-460b-9a75-a40e030a5458"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(9240),
                            DateOfBorn = new DateTime(2016, 6, 28, 1, 5, 34, 553, DateTimeKind.Unspecified).AddTicks(4840),
                            Email = "D.Weaver@microsoft.info",
                            Name = "Evan",
                            Surname = "Wright",
                            Title = "lego.co.uk"
                        },
                        new
                        {
                            Id = new Guid("14acfd1f-89ea-47e1-819c-6d8f5334c578"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 6, 37, 278, DateTimeKind.Local).AddTicks(9304),
                            DateOfBorn = new DateTime(1996, 2, 4, 18, 40, 57, 510, DateTimeKind.Unspecified).AddTicks(4713),
                            Email = "Piper.Shepherd@deviantart.org",
                            Name = "Jason",
                            Surname = "Wilson",
                            Title = "ask.biz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
