// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20201122013736_s5")]
    partial class s5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0ac2a5c-b1f4-4487-8b85-8b27f3df76d3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 744, DateTimeKind.Local).AddTicks(5061),
                            Email = "S.Brown@flipkart.co.uk",
                            Experience = 4,
                            Name = "Zoe",
                            Surname = "Evans",
                            Title = "yelp.co.uk"
                        },
                        new
                        {
                            Id = new Guid("dd015505-f3b2-466f-b9bd-f2a651c0c5c0"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(3783),
                            Email = "H.Haines@taobao.co.uk",
                            Experience = 9,
                            Name = "Maya",
                            Surname = "Mann",
                            Title = "google.us"
                        },
                        new
                        {
                            Id = new Guid("d1a06896-5808-4d1f-b4a9-52cf9d4d65fb"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8411),
                            Email = "A.Barlow@bbc.us",
                            Experience = 17,
                            Name = "Ariana",
                            Surname = "Riddick",
                            Title = "paypal.info"
                        },
                        new
                        {
                            Id = new Guid("7331fc8e-1666-44e1-9bae-e1360860c026"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8494),
                            Email = "Luis.Taylor@microsoft.com",
                            Experience = 9,
                            Name = "Cameron",
                            Surname = "Mclean",
                            Title = "wikipedia.org.uk"
                        },
                        new
                        {
                            Id = new Guid("5b92af35-1895-4059-b9a9-33be1e391d8e"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8555),
                            Email = "Liam.Taylor@paypal.com",
                            Experience = 4,
                            Name = "Joseph",
                            Surname = "Hancock",
                            Title = "etsy.com"
                        },
                        new
                        {
                            Id = new Guid("c960ffd6-577d-4767-bbfe-33ff7fe2effc"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8615),
                            Email = "V.Peters@youtube.info",
                            Experience = 10,
                            Name = "John",
                            Surname = "Vaughan",
                            Title = "amazon.org.uk"
                        },
                        new
                        {
                            Id = new Guid("4ba09cad-037e-4aad-b78f-15db1b95997e"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8640),
                            Email = "Justin.Osborne@qq.info",
                            Experience = 2,
                            Name = "Riley",
                            Surname = "Thompson",
                            Title = "baidu.us"
                        },
                        new
                        {
                            Id = new Guid("5879e979-9f10-4446-abaf-b50e2f3e89c4"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8743),
                            Email = "Cameron.Jones@etsy.co.uk",
                            Experience = 13,
                            Name = "William",
                            Surname = "Mclean",
                            Title = "ask.co.uk"
                        },
                        new
                        {
                            Id = new Guid("1504665e-0564-4ddb-8168-374ddd84e3b9"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8775),
                            Email = "Nathan.Brown@wikipedia.com",
                            Experience = 22,
                            Name = "Charlotte",
                            Surname = "Mcgrath",
                            Title = "ask.us"
                        },
                        new
                        {
                            Id = new Guid("e29873ee-6222-401f-9ec1-63d5af341860"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8833),
                            Email = "M.Baldwin@gmail.org.uk",
                            Experience = 17,
                            Name = "Juan",
                            Surname = "Nelson",
                            Title = "techcrunch.net"
                        },
                        new
                        {
                            Id = new Guid("c1b48c8d-6690-4d7e-8011-ce60fb3f6fce"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8856),
                            Email = "L.Boyd@yelp.biz",
                            Experience = 16,
                            Name = "Mackenzie",
                            Surname = "Lindsay",
                            Title = "youtube.net"
                        },
                        new
                        {
                            Id = new Guid("7ee9dc57-ded7-4c63-a474-3426b9f05d01"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8912),
                            Email = "Owen.Giles@flipkart.co.uk",
                            Experience = 22,
                            Name = "London",
                            Surname = "Johnson",
                            Title = "live.us"
                        },
                        new
                        {
                            Id = new Guid("52daa634-f2cf-42cf-8df2-29370b634d98"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8933),
                            Email = "London.Carroll@bing.org.uk",
                            Experience = 4,
                            Name = "Hannah",
                            Surname = "Bradshaw",
                            Title = "google.co.uk"
                        },
                        new
                        {
                            Id = new Guid("29da82d8-6575-47ef-a07f-be9a656d3e9b"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(8987),
                            Email = "J.Vaughan@msdn.org",
                            Experience = 10,
                            Name = "Emma",
                            Surname = "Obrien",
                            Title = "studio1337.org.uk"
                        },
                        new
                        {
                            Id = new Guid("05977c8d-3d18-4c8b-859d-c9f803968d62"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9009),
                            Email = "C.Jackson@ebay.co",
                            Experience = 22,
                            Name = "Parker",
                            Surname = "Little",
                            Title = "paypal.co"
                        },
                        new
                        {
                            Id = new Guid("8ff56d48-7648-4eb8-8361-12a5a3e643a3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9064),
                            Email = "Jasmine.Mcfarlane@etsy.com",
                            Experience = 9,
                            Name = "Melanie",
                            Surname = "Swift",
                            Title = "live.net"
                        },
                        new
                        {
                            Id = new Guid("f2d098a4-c68c-4666-b1d5-5a9170a0eb0d"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9178),
                            Email = "Alexandra.Thompson@sohu.us",
                            Experience = 29,
                            Name = "Alexa",
                            Surname = "Shepherd",
                            Title = "cnn.com"
                        },
                        new
                        {
                            Id = new Guid("b7daafe8-0170-464b-80b4-4ae831b5f633"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9203),
                            Email = "S.Savage@ask.org.uk",
                            Experience = 20,
                            Name = "Jocelyn",
                            Surname = "Johnson",
                            Title = "live.co.uk"
                        },
                        new
                        {
                            Id = new Guid("823e2225-2cb9-43f7-9e18-f6ba45627f8f"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9258),
                            Email = "A.Barlow@bestbuy.org",
                            Experience = 3,
                            Name = "Leah",
                            Surname = "Seymour",
                            Title = "ask.org"
                        },
                        new
                        {
                            Id = new Guid("0203dae6-8b77-4ba3-ab4a-935041be8735"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9282),
                            Email = "Andrew.Davies@163.org.uk",
                            Experience = 19,
                            Name = "Lucy",
                            Surname = "Mac",
                            Title = "wordpress.co"
                        },
                        new
                        {
                            Id = new Guid("6c0f7c84-5503-451e-ba25-213f793dd150"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9336),
                            Email = "Levi.Cullen@wikia.co",
                            Experience = 26,
                            Name = "Dylan",
                            Surname = "Perkins",
                            Title = "microsoft.org.uk"
                        },
                        new
                        {
                            Id = new Guid("d52dae8a-fd27-4991-bffb-3f7bd7e32d75"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9357),
                            Email = "Claire.Joyce@stackoverflow.org",
                            Experience = 25,
                            Name = "Faith",
                            Surname = "Haines",
                            Title = "paypal.org"
                        },
                        new
                        {
                            Id = new Guid("35c75091-f172-4ef1-9b3f-227b61bc6aac"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9429),
                            Email = "Aubrey.Mcfarlane@sohu.info",
                            Experience = 28,
                            Name = "Isaiah",
                            Surname = "Mellor",
                            Title = "bet365.com"
                        },
                        new
                        {
                            Id = new Guid("9cb8f509-8d16-4db4-9c39-d00fd18d20c7"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9451),
                            Email = "Ian.Weaver@bbc.co.uk",
                            Experience = 10,
                            Name = "Wyatt",
                            Surname = "Lewis",
                            Title = "expedia.com"
                        },
                        new
                        {
                            Id = new Guid("0f3d2705-afe1-4e1c-b85b-9282326a3f3f"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9506),
                            Email = "J.Leach@linkedin.us",
                            Experience = 9,
                            Name = "Daniel",
                            Surname = "Bradshaw",
                            Title = "cnn.co"
                        },
                        new
                        {
                            Id = new Guid("8bf836b2-73a5-4c3c-bb5f-ef07e6e6034a"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9529),
                            Email = "Sophia.Perkins@amazon.org",
                            Experience = 11,
                            Name = "Kayla",
                            Surname = "Dale",
                            Title = "techcrunch.info"
                        },
                        new
                        {
                            Id = new Guid("4035bbcb-3447-4a5e-8ebc-feab5505c471"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9583),
                            Email = "M.Stuart@theguardian.us",
                            Experience = 10,
                            Name = "Savannah",
                            Surname = "Power",
                            Title = "gmail.org"
                        },
                        new
                        {
                            Id = new Guid("b13adf37-3896-4d83-8849-8132e1f2cc08"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9605),
                            Email = "M.Mclean@wordpress.com",
                            Experience = 21,
                            Name = "Grayson",
                            Surname = "Dale",
                            Title = "qq.org"
                        },
                        new
                        {
                            Id = new Guid("4c4ae39d-baeb-481b-9a20-8e44e90d57e3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9660),
                            Email = "Wyatt.Nash@expedia.info",
                            Experience = 2,
                            Name = "Matthew",
                            Surname = "Lindsay",
                            Title = "sohu.org.uk"
                        },
                        new
                        {
                            Id = new Guid("ff285214-e0f7-4559-8e26-769d4b73f8d5"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9680),
                            Email = "Alexa.Mcfarlane@bbc.com",
                            Experience = 26,
                            Name = "Caleb",
                            Surname = "Thorne",
                            Title = "taobao.net"
                        },
                        new
                        {
                            Id = new Guid("0e27a653-b5bb-43b8-baef-4a9b5b339c69"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9735),
                            Email = "Zoe.Seymour@expedia.co.uk",
                            Experience = 21,
                            Name = "Zoe",
                            Surname = "Giles",
                            Title = "sky.org.uk"
                        },
                        new
                        {
                            Id = new Guid("28e3c2f6-5c2a-41e0-89df-888187049c65"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9787),
                            Email = "Sophie.Walters@linkedin.com",
                            Experience = 11,
                            Name = "Jack",
                            Surname = "Hilton",
                            Title = "paypal.org"
                        },
                        new
                        {
                            Id = new Guid("f9a654ac-5e71-46d3-951d-164e9b023a85"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9811),
                            Email = "K.Roberts@deviantart.com",
                            Experience = 2,
                            Name = "Hudson",
                            Surname = "Mcfarlane",
                            Title = "etsy.com"
                        },
                        new
                        {
                            Id = new Guid("8d478eb3-2baa-4a1c-bb06-be72d3659410"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9868),
                            Email = "C.Shepherd@lego.co.uk",
                            Experience = 4,
                            Name = "Aaron",
                            Surname = "Sinclair",
                            Title = "bbc.co"
                        },
                        new
                        {
                            Id = new Guid("9cdab2a9-7a8f-4ba9-a5d7-863c20369c0c"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9891),
                            Email = "R.Jones@amazon.biz",
                            Experience = 11,
                            Name = "Kylie",
                            Surname = "Akhtar",
                            Title = "maplin.org.uk"
                        },
                        new
                        {
                            Id = new Guid("3a3d3385-b885-4cb8-8aae-5c6dd804acea"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9945),
                            Email = "J.Bradshaw@ask.co",
                            Experience = 18,
                            Name = "Zoey",
                            Surname = "Nelson",
                            Title = "ebay.info"
                        },
                        new
                        {
                            Id = new Guid("9f7fc160-7887-4610-8134-fadac68cf378"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 748, DateTimeKind.Local).AddTicks(9967),
                            Email = "K.Blair@baidu.biz",
                            Experience = 26,
                            Name = "Sophie",
                            Surname = "Brown",
                            Title = "techcrunch.com"
                        },
                        new
                        {
                            Id = new Guid("18834bfa-e3b7-4258-84f9-607b588e53d1"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(38),
                            Email = "J.Mellor@stackoverflow.co",
                            Experience = 16,
                            Name = "Grace",
                            Surname = "Akhtar",
                            Title = "sky.org.uk"
                        },
                        new
                        {
                            Id = new Guid("fd82277d-7c32-449b-91cd-8dc93e5fcce8"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(60),
                            Email = "Peyton.Mann@microsoft.co.uk",
                            Experience = 16,
                            Name = "Joseph",
                            Surname = "Swift",
                            Title = "bestbuy.com"
                        },
                        new
                        {
                            Id = new Guid("260683da-8668-46dd-8b8d-def3abff0afa"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(114),
                            Email = "Blake.Joyce@ask.net",
                            Experience = 15,
                            Name = "Julian",
                            Surname = "Davies",
                            Title = "amazon.net"
                        },
                        new
                        {
                            Id = new Guid("b99c063d-37f4-482c-a6ad-c60f218cbddc"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(137),
                            Email = "Jasmine.Green@maplin.co",
                            Experience = 20,
                            Name = "Trinity",
                            Surname = "Smith",
                            Title = "lego.net"
                        },
                        new
                        {
                            Id = new Guid("f57ba8d3-cdaf-4a8a-8f04-e83e7a684223"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(222),
                            Email = "M.Briggs@globo.biz",
                            Experience = 16,
                            Name = "Gianna",
                            Surname = "Brown",
                            Title = "yelp.us"
                        },
                        new
                        {
                            Id = new Guid("b9f02002-c879-449c-a0f5-1e677a8b62a7"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(244),
                            Email = "A.Evans@studio1337.com",
                            Experience = 29,
                            Name = "Tyler",
                            Surname = "Cassidy",
                            Title = "163.org"
                        },
                        new
                        {
                            Id = new Guid("69265a1a-70b7-4ac7-a98a-b6ca878225c4"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(300),
                            Email = "L.Giles@pinterest.co",
                            Experience = 19,
                            Name = "Logan",
                            Surname = "Wood",
                            Title = "bing.biz"
                        },
                        new
                        {
                            Id = new Guid("c6bf770d-b6a1-4276-b7f1-b8e43a767c95"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(357),
                            Email = "Sophia.Baldwin@cnn.org",
                            Experience = 29,
                            Name = "Aaron",
                            Surname = "Giles",
                            Title = "amazon.org"
                        },
                        new
                        {
                            Id = new Guid("d2820f8f-3dd2-400f-88ae-a748039915f5"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(379),
                            Email = "N.Hooper@163.org.uk",
                            Experience = 23,
                            Name = "Luis",
                            Surname = "Lord",
                            Title = "studio1337.org.uk"
                        },
                        new
                        {
                            Id = new Guid("aa6a7c9d-c043-47bb-aaf8-fbd97e800590"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(433),
                            Email = "O.White@theguardian.co.uk",
                            Experience = 21,
                            Name = "Jasmine",
                            Surname = "Vaughan",
                            Title = "gmail.net"
                        },
                        new
                        {
                            Id = new Guid("aa2d33be-9ad9-43af-a4ca-b40448e372fd"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(456),
                            Email = "C.Osborne@sky.net",
                            Experience = 18,
                            Name = "Tyler",
                            Surname = "Vaughan",
                            Title = "microsoft.co.uk"
                        },
                        new
                        {
                            Id = new Guid("d61eb641-2818-4c1d-99f1-ec8a00b97880"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(513),
                            Email = "E.Bradshaw@bet365.net",
                            Experience = 4,
                            Name = "Oliver",
                            Surname = "Jones",
                            Title = "yelp.info"
                        },
                        new
                        {
                            Id = new Guid("64369670-64e0-40ae-aab1-6df64bf55a24"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(535),
                            Email = "S.Haines@lego.info",
                            Experience = 24,
                            Name = "Jocelyn",
                            Surname = "Peters",
                            Title = "gmail.co.uk"
                        },
                        new
                        {
                            Id = new Guid("daeccd76-c5f1-4d98-b8e6-51bfacd5630d"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(589),
                            Email = "I.Buckley@wikia.com",
                            Experience = 28,
                            Name = "Lucas",
                            Surname = "Welch",
                            Title = "studio1337.co.uk"
                        },
                        new
                        {
                            Id = new Guid("c73f0df1-489f-4201-b050-3e2b1cd93758"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(610),
                            Email = "Bailey.Abbott@ask.co.uk",
                            Experience = 15,
                            Name = "Nathaniel",
                            Surname = "Blair",
                            Title = "bet365.net"
                        },
                        new
                        {
                            Id = new Guid("c0de0e05-58f2-447e-a270-400d91216175"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(678),
                            Email = "C.Thompson@sohu.org.uk",
                            Experience = 1,
                            Name = "Xavier",
                            Surname = "Joyce",
                            Title = "wordpress.org"
                        },
                        new
                        {
                            Id = new Guid("07c79ab4-e31f-4a25-bc18-6dd18fba9a19"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(701),
                            Email = "Sydney.Welch@techcrunch.biz",
                            Experience = 19,
                            Name = "Nevaeh",
                            Surname = "Vaughan",
                            Title = "globo.com"
                        },
                        new
                        {
                            Id = new Guid("7b61ec9d-e13b-43cf-a65b-d38c5b2726a0"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(756),
                            Email = "Katherine.Mac@youtube.us",
                            Experience = 23,
                            Name = "Chloe",
                            Surname = "Taylor",
                            Title = "paypal.org.uk"
                        },
                        new
                        {
                            Id = new Guid("2b8b46a9-27d8-47d7-82f0-25eddce34133"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(777),
                            Email = "Adrian.Coles@deviantart.net",
                            Experience = 2,
                            Name = "Gabriel",
                            Surname = "Silva",
                            Title = "paypal.net"
                        },
                        new
                        {
                            Id = new Guid("9b14adf4-72bc-45bc-98ac-0ec9c745768d"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(833),
                            Email = "Ella.Blair@gmail.co.uk",
                            Experience = 3,
                            Name = "Naomi",
                            Surname = "Mohamed",
                            Title = "lego.biz"
                        },
                        new
                        {
                            Id = new Guid("dc1faa12-69b3-4160-93d0-6c24f2396a2c"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(853),
                            Email = "C.Wright@paypal.co",
                            Experience = 3,
                            Name = "Molly",
                            Surname = "Briggs",
                            Title = "ebay.com"
                        },
                        new
                        {
                            Id = new Guid("bf9edb44-1257-434d-b6ab-0f8043cd9674"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(909),
                            Email = "Landon.Osborne@taobao.org.uk",
                            Experience = 19,
                            Name = "Isaiah",
                            Surname = "Burrows",
                            Title = "msdn.com"
                        },
                        new
                        {
                            Id = new Guid("3e74ab28-3e79-42f7-8370-d08fe6897f9b"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(962),
                            Email = "A.Chadwick@bing.info",
                            Experience = 22,
                            Name = "Elijah",
                            Surname = "Mohamed",
                            Title = "bestbuy.org.uk"
                        },
                        new
                        {
                            Id = new Guid("320e716c-e5eb-4800-b001-3c0989923044"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(984),
                            Email = "M.Whittaker@msdn.co.uk",
                            Experience = 2,
                            Name = "Jacob",
                            Surname = "Savage",
                            Title = "cnn.org.uk"
                        },
                        new
                        {
                            Id = new Guid("ae470506-aaf7-4dc4-9de9-8258302bd83d"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1040),
                            Email = "S.Haines@wikipedia.co",
                            Experience = 9,
                            Name = "Jace",
                            Surname = "Shepherd",
                            Title = "qq.com"
                        },
                        new
                        {
                            Id = new Guid("837176e0-54e1-4dc8-8bac-c31a6f1a59e3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1061),
                            Email = "Ashley.Whittaker@arstechnica.info",
                            Experience = 3,
                            Name = "Charlotte",
                            Surname = "Welch",
                            Title = "cnn.info"
                        },
                        new
                        {
                            Id = new Guid("f18ab73f-fec2-42d3-9d61-750d74864628"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1115),
                            Email = "K.Smith@gmail.co.uk",
                            Experience = 27,
                            Name = "Ryan",
                            Surname = "Barlow",
                            Title = "techcrunch.org.uk"
                        },
                        new
                        {
                            Id = new Guid("2e80d80c-38e6-48ed-ba1e-e59d68fff0ba"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1139),
                            Email = "Sophie.Barlow@linkedin.org",
                            Experience = 19,
                            Name = "Julia",
                            Surname = "Bradshaw",
                            Title = "maplin.us"
                        },
                        new
                        {
                            Id = new Guid("3266d567-833e-4568-b532-7a4aa96be6a3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1223),
                            Email = "Chloe.Mohamed@wordpress.net",
                            Experience = 24,
                            Name = "Makayla",
                            Surname = "Evans",
                            Title = "qq.us"
                        },
                        new
                        {
                            Id = new Guid("e57a2050-f182-439c-85b1-29a2248ed730"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1245),
                            Email = "Z.Evans@studio1337.com",
                            Experience = 10,
                            Name = "Ryder",
                            Surname = "Weaver",
                            Title = "deviantart.com"
                        },
                        new
                        {
                            Id = new Guid("19fd2e25-fcf9-4df7-b067-fa30c8a4c285"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1314),
                            Email = "L.Nelson@microsoft.co",
                            Experience = 11,
                            Name = "Riley",
                            Surname = "Wyatt",
                            Title = "sky.net"
                        },
                        new
                        {
                            Id = new Guid("6007a1af-6b05-401d-87a5-93476c5e2ded"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1336),
                            Email = "N.Boyd@163.co.uk",
                            Experience = 10,
                            Name = "Olivia",
                            Surname = "Mcgrath",
                            Title = "deviantart.co"
                        },
                        new
                        {
                            Id = new Guid("71e4d637-b2b6-4f41-a113-35118c0742ec"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1394),
                            Email = "Bailey.Abbott@adamriddick.net",
                            Experience = 20,
                            Name = "Ayden",
                            Surname = "Abbott",
                            Title = "globo.info"
                        },
                        new
                        {
                            Id = new Guid("d94d51a3-e5c0-442a-819a-17b08d937698"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1448),
                            Email = "K.Wood@microsoft.co.uk",
                            Experience = 5,
                            Name = "Caleb",
                            Surname = "Mohamed",
                            Title = "sohu.biz"
                        },
                        new
                        {
                            Id = new Guid("ae82b892-c02c-4bbb-8208-e02220d87fba"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1470),
                            Email = "T.Harris@bet365.biz",
                            Experience = 2,
                            Name = "Blake",
                            Surname = "Mohamed",
                            Title = "ebay.net"
                        },
                        new
                        {
                            Id = new Guid("de32a0c5-b01e-45b5-bbbe-797a22c5ccc8"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1527),
                            Email = "C.Haines@etsy.net",
                            Experience = 19,
                            Name = "Victoria",
                            Surname = "Hilton",
                            Title = "youtube.co.uk"
                        },
                        new
                        {
                            Id = new Guid("803db8fd-104f-4460-993e-978a20cda644"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1548),
                            Email = "Adrian.Shepherd@yahoo.org",
                            Experience = 7,
                            Name = "Skylar",
                            Surname = "Taylor",
                            Title = "baidu.co.uk"
                        },
                        new
                        {
                            Id = new Guid("5eaf1719-a38e-4d58-8fca-ae6f8fce3925"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1601),
                            Email = "D.Davies@sohu.org",
                            Experience = 23,
                            Name = "Camila",
                            Surname = "Jones",
                            Title = "live.biz"
                        },
                        new
                        {
                            Id = new Guid("b0d5252a-7210-4f7d-a2fd-a112ba1f0225"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1623),
                            Email = "G.Kenny@globo.org.uk",
                            Experience = 26,
                            Name = "Sebastian",
                            Surname = "Savage",
                            Title = "bing.org.uk"
                        },
                        new
                        {
                            Id = new Guid("1269b5f4-4608-40b5-8220-598a93e30c52"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1683),
                            Email = "Tristan.Walters@cnn.co",
                            Experience = 12,
                            Name = "Chloe",
                            Surname = "Thompson",
                            Title = "paypal.net"
                        },
                        new
                        {
                            Id = new Guid("81c5e46a-fdd7-4fda-a76d-f87355a8b364"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1705),
                            Email = "Grace.Joyce@msdn.info",
                            Experience = 3,
                            Name = "Alexa",
                            Surname = "Wyatt",
                            Title = "arstechnica.co"
                        },
                        new
                        {
                            Id = new Guid("36375a9b-ac9f-4763-a97c-31769f45a7ee"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1759),
                            Email = "Blake.Dale@msdn.info",
                            Experience = 4,
                            Name = "Camila",
                            Surname = "Whittaker",
                            Title = "paypal.co.uk"
                        },
                        new
                        {
                            Id = new Guid("151addfe-1086-4b41-88ae-25ed24b91b84"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1780),
                            Email = "Daniel.Shepherd@globo.co.uk",
                            Experience = 28,
                            Name = "Makayla",
                            Surname = "Walters",
                            Title = "amazon.org.uk"
                        },
                        new
                        {
                            Id = new Guid("61c29678-d0e9-4009-8c2b-bea147b01187"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1836),
                            Email = "Juan.Green@bbc.net",
                            Experience = 3,
                            Name = "Brianna",
                            Surname = "Harris",
                            Title = "globo.org.uk"
                        },
                        new
                        {
                            Id = new Guid("49f57c40-58fd-4f97-baca-2bf142f0f9a3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1857),
                            Email = "K.Carroll@adamriddick.org.uk",
                            Experience = 26,
                            Name = "Madeline",
                            Surname = "Mac",
                            Title = "wikipedia.us"
                        },
                        new
                        {
                            Id = new Guid("ba24e02d-77bd-441b-90da-c0bd12f2cb68"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1926),
                            Email = "Bella.Power@expedia.us",
                            Experience = 1,
                            Name = "Aiden",
                            Surname = "Jones",
                            Title = "cnn.org.uk"
                        },
                        new
                        {
                            Id = new Guid("b7fb4da4-6f5b-42f3-9c84-385efe48ad3c"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(1947),
                            Email = "Nathan.Mellor@globo.org.uk",
                            Experience = 1,
                            Name = "Dylan",
                            Surname = "Robinson",
                            Title = "adamriddick.co"
                        },
                        new
                        {
                            Id = new Guid("363ee5e8-467f-42d9-987d-3ec2d7c6f074"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2001),
                            Email = "Hudson.Power@sohu.co",
                            Experience = 23,
                            Name = "Natalie",
                            Surname = "Whelan",
                            Title = "globo.com"
                        },
                        new
                        {
                            Id = new Guid("2c613847-5e56-4ad3-b328-45bb95befa3c"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2022),
                            Email = "Ashley.Akhtar@etsy.biz",
                            Experience = 5,
                            Name = "Robert",
                            Surname = "Nash",
                            Title = "linkedin.info"
                        },
                        new
                        {
                            Id = new Guid("454136df-8444-42b7-9d74-8c50afea46e5"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2076),
                            Email = "J.Mac@etsy.info",
                            Experience = 5,
                            Name = "Jace",
                            Surname = "Watson",
                            Title = "youtube.com"
                        },
                        new
                        {
                            Id = new Guid("3c2d99d1-4dbf-479f-a24a-daeb8fc3a8aa"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2131),
                            Email = "Liam.Riddick@wordpress.com",
                            Experience = 4,
                            Name = "Kimberly",
                            Surname = "Robinson",
                            Title = "amazon.org.uk"
                        },
                        new
                        {
                            Id = new Guid("99fec8de-6bb4-4234-8ee5-ffcfd137453b"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2154),
                            Email = "A.Wright@amazon.com",
                            Experience = 27,
                            Name = "Christopher",
                            Surname = "Mellor",
                            Title = "sohu.us"
                        },
                        new
                        {
                            Id = new Guid("5ff34701-2a99-41c3-bb73-e22dc9927cf6"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2234),
                            Email = "Z.Vaughan@maplin.org.uk",
                            Experience = 14,
                            Name = "Bentley",
                            Surname = "Abbott",
                            Title = "lego.org"
                        },
                        new
                        {
                            Id = new Guid("1120697b-5a0c-4587-9f08-6c2d452a300b"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2257),
                            Email = "Justin.Buckley@arstechnica.biz",
                            Experience = 3,
                            Name = "Grayson",
                            Surname = "Wyatt",
                            Title = "adamriddick.co.uk"
                        },
                        new
                        {
                            Id = new Guid("84ba5f55-404a-4a84-97a2-541bb8718b12"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2312),
                            Email = "Trinity.Buckley@cnn.biz",
                            Experience = 11,
                            Name = "Dylan",
                            Surname = "Schofield",
                            Title = "qq.co.uk"
                        },
                        new
                        {
                            Id = new Guid("de7a091e-f3b2-450c-969c-37457105e65d"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2333),
                            Email = "M.Silva@wordpress.co",
                            Experience = 11,
                            Name = "Samantha",
                            Surname = "Mcfarlane",
                            Title = "sohu.info"
                        },
                        new
                        {
                            Id = new Guid("6dd67f7f-f3eb-4ba5-9db6-2bf1ad47bf45"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2388),
                            Email = "R.Mann@msdn.co",
                            Experience = 12,
                            Name = "Blake",
                            Surname = "Barlow",
                            Title = "maplin.org"
                        },
                        new
                        {
                            Id = new Guid("e8bfded8-0650-4b24-b462-3ecb13c5a413"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2410),
                            Email = "Tyler.Thorne@stackoverflow.info",
                            Experience = 17,
                            Name = "Emma",
                            Surname = "Whitehouse",
                            Title = "stackoverflow.net"
                        },
                        new
                        {
                            Id = new Guid("56d60c20-d965-4e6d-8099-b485456303d3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2464),
                            Email = "H.Sanders@163.net",
                            Experience = 18,
                            Name = "Victoria",
                            Surname = "Barlow",
                            Title = "yahoo.com"
                        },
                        new
                        {
                            Id = new Guid("fb55c5bf-e163-492f-acd6-0ae49d123265"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2488),
                            Email = "P.Taylor@flipkart.org.uk",
                            Experience = 5,
                            Name = "Dominic",
                            Surname = "Buckley",
                            Title = "globo.info"
                        },
                        new
                        {
                            Id = new Guid("ce575f22-9840-46f1-9ccf-9385f19d8269"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2556),
                            Email = "Alex.Mclean@yelp.biz",
                            Experience = 13,
                            Name = "Piper",
                            Surname = "Jennings",
                            Title = "yelp.info"
                        },
                        new
                        {
                            Id = new Guid("0eae5dbf-bd8c-4694-ac17-f2576e9482e3"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2577),
                            Email = "G.Lindsay@maplin.us",
                            Experience = 8,
                            Name = "Piper",
                            Surname = "Buckley",
                            Title = "pinterest.info"
                        },
                        new
                        {
                            Id = new Guid("c79eed1d-4796-454d-864f-867f262b6615"),
                            AddedDate = new DateTime(2020, 11, 22, 4, 37, 35, 749, DateTimeKind.Local).AddTicks(2631),
                            Email = "Cameron.Hancock@flipkart.org.uk",
                            Experience = 18,
                            Name = "Jaxon",
                            Surname = "Haines",
                            Title = "bet365.co"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
