// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20201120110318_s2")]
    partial class s2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBorn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81980971-b2a6-4b5b-bbe8-49a222ac9972"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 55, DateTimeKind.Local).AddTicks(2998),
                            DateOfBorn = new DateTime(2019, 11, 5, 15, 11, 40, 923, DateTimeKind.Unspecified).AddTicks(7714),
                            Email = "E.Mac@amazon.co",
                            Name = "Blake",
                            Surname = "Thorne",
                            Title = "ebay.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(2930)
                        },
                        new
                        {
                            Id = new Guid("ae27601e-a9c3-4dad-b7f3-ba87adda1cf9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3497),
                            DateOfBorn = new DateTime(2002, 10, 30, 21, 30, 50, 717, DateTimeKind.Unspecified).AddTicks(1390),
                            Email = "Grace.Summers@bbc.net",
                            Name = "Bella",
                            Surname = "Mohamed",
                            Title = "linkedin.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3709)
                        },
                        new
                        {
                            Id = new Guid("cbdbbd28-0150-42f3-b051-2eac3bcb60b5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3763),
                            DateOfBorn = new DateTime(1972, 11, 11, 20, 34, 35, 753, DateTimeKind.Unspecified).AddTicks(553),
                            Email = "London.Buckley@bet365.com",
                            Name = "Lucy",
                            Surname = "Thornton",
                            Title = "yahoo.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3791)
                        },
                        new
                        {
                            Id = new Guid("d33ed60b-0d1b-4148-92d0-08f0df3fa555"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3792),
                            DateOfBorn = new DateTime(2016, 9, 11, 9, 58, 16, 536, DateTimeKind.Unspecified).AddTicks(1130),
                            Email = "L.Wood@live.com",
                            Name = "Luke",
                            Surname = "Rossi",
                            Title = "wikia.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3906)
                        },
                        new
                        {
                            Id = new Guid("77a71a53-af73-486e-8ba4-49f18c55dc36"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3908),
                            DateOfBorn = new DateTime(1976, 12, 28, 15, 20, 10, 421, DateTimeKind.Unspecified).AddTicks(2985),
                            Email = "S.Schofield@taobao.org",
                            Name = "Gianna",
                            Surname = "Thompson",
                            Title = "adamriddick.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3932)
                        },
                        new
                        {
                            Id = new Guid("817b9cc5-0286-48af-9882-79c4e81c8b6a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3936),
                            DateOfBorn = new DateTime(2016, 3, 16, 4, 15, 7, 29, DateTimeKind.Unspecified).AddTicks(8016),
                            Email = "Isaiah.Whitehouse@maplin.co.uk",
                            Name = "Alyssa",
                            Surname = "Lindsay",
                            Title = "qq.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(3999)
                        },
                        new
                        {
                            Id = new Guid("ce47f87e-cf3f-45ba-b0ec-48582229af69"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4001),
                            DateOfBorn = new DateTime(1998, 6, 24, 0, 0, 37, 424, DateTimeKind.Unspecified).AddTicks(3559),
                            Email = "G.Akhtar@yahoo.org.uk",
                            Name = "Brody",
                            Surname = "Hooper",
                            Title = "arstechnica.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4035)
                        },
                        new
                        {
                            Id = new Guid("669e8e46-6e04-4477-bc6d-2761b43be06e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4036),
                            DateOfBorn = new DateTime(1977, 7, 31, 17, 34, 2, 456, DateTimeKind.Unspecified).AddTicks(5682),
                            Email = "Autumn.Blair@globo.co",
                            Name = "Evelyn",
                            Surname = "Whitehouse",
                            Title = "bbc.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            Id = new Guid("949c1fc6-2778-4b66-b1cd-461f6a21507b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4192),
                            DateOfBorn = new DateTime(2007, 12, 2, 1, 5, 36, 988, DateTimeKind.Unspecified).AddTicks(2996),
                            Email = "A.Summers@globo.co",
                            Name = "Reagan",
                            Surname = "Lindsay",
                            Title = "lego.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4217)
                        },
                        new
                        {
                            Id = new Guid("13509399-9060-495b-9187-9c2d8a380251"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4220),
                            DateOfBorn = new DateTime(1974, 5, 15, 13, 8, 22, 610, DateTimeKind.Unspecified).AddTicks(9982),
                            Email = "K.Brown@studio1337.com",
                            Name = "Scott",
                            Surname = "Seymour",
                            Title = "wikia.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4289)
                        },
                        new
                        {
                            Id = new Guid("e4ffefec-0a6a-4003-93c5-b41e27aa1869"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4290),
                            DateOfBorn = new DateTime(1994, 5, 9, 4, 24, 5, 250, DateTimeKind.Unspecified).AddTicks(3458),
                            Email = "Autumn.Abbott@theguardian.org.uk",
                            Name = "Victoria",
                            Surname = "Cullen",
                            Title = "live.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4311)
                        },
                        new
                        {
                            Id = new Guid("1e790f4c-7e8c-4a1d-9550-3c48446e2496"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4312),
                            DateOfBorn = new DateTime(2020, 1, 6, 11, 27, 6, 197, DateTimeKind.Unspecified).AddTicks(5354),
                            Email = "L.Power@globo.org.uk",
                            Name = "Zachary",
                            Surname = "Mellor",
                            Title = "youtube.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4381)
                        },
                        new
                        {
                            Id = new Guid("87a048f2-95ec-40d4-ac50-18d1e2236ebf"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4383),
                            DateOfBorn = new DateTime(2007, 12, 16, 8, 50, 34, 407, DateTimeKind.Unspecified).AddTicks(1052),
                            Email = "Kevin.Barlow@youtube.org.uk",
                            Name = "Aria",
                            Surname = "Rossi",
                            Title = "maplin.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4405)
                        },
                        new
                        {
                            Id = new Guid("cedac1db-850a-49ac-8265-0d9bf0b87b18"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4406),
                            DateOfBorn = new DateTime(2002, 7, 5, 20, 54, 8, 691, DateTimeKind.Unspecified).AddTicks(6362),
                            Email = "E.Riddick@wikipedia.org.uk",
                            Name = "Noah",
                            Surname = "Osborne",
                            Title = "pinterest.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4467)
                        },
                        new
                        {
                            Id = new Guid("b7aa2c6c-e53e-4934-bde2-f0b6b7ebda0d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4468),
                            DateOfBorn = new DateTime(1992, 1, 1, 16, 12, 4, 373, DateTimeKind.Unspecified).AddTicks(6863),
                            Email = "B.Thomas@techcrunch.co.uk",
                            Name = "Zoe",
                            Surname = "Boyd",
                            Title = "ask.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4494)
                        },
                        new
                        {
                            Id = new Guid("36c46a8c-cc97-42ce-9845-e2cae81b0696"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4495),
                            DateOfBorn = new DateTime(1999, 7, 30, 1, 24, 0, 79, DateTimeKind.Unspecified).AddTicks(9989),
                            Email = "Nolan.Lewis@google.co.uk",
                            Name = "David",
                            Surname = "Mac",
                            Title = "yahoo.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4565)
                        },
                        new
                        {
                            Id = new Guid("d141fa5d-329c-4916-84e2-d9d0f9495f10"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4567),
                            DateOfBorn = new DateTime(1984, 1, 21, 13, 51, 48, 49, DateTimeKind.Unspecified).AddTicks(9917),
                            Email = "E.Akhtar@theguardian.info",
                            Name = "Hudson",
                            Surname = "Williams",
                            Title = "linkedin.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4629)
                        },
                        new
                        {
                            Id = new Guid("fb3a870b-f7a8-4864-9e7f-cd068314c9a1"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4633),
                            DateOfBorn = new DateTime(1987, 12, 11, 14, 27, 58, 717, DateTimeKind.Unspecified).AddTicks(736),
                            Email = "B.Giles@bbc.org",
                            Name = "Skylar",
                            Surname = "Obrien",
                            Title = "expedia.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4656)
                        },
                        new
                        {
                            Id = new Guid("6265e937-2130-451a-a63f-6ccd965bd7fd"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4658),
                            DateOfBorn = new DateTime(2016, 3, 1, 0, 53, 47, 88, DateTimeKind.Unspecified).AddTicks(5798),
                            Email = "Allison.Mellor@wikia.org",
                            Name = "Sarah",
                            Surname = "Jones",
                            Title = "cnn.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4736)
                        },
                        new
                        {
                            Id = new Guid("a2a287be-6f11-4e00-a7de-4155e0863424"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4738),
                            DateOfBorn = new DateTime(1982, 8, 25, 17, 4, 53, 561, DateTimeKind.Unspecified).AddTicks(8562),
                            Email = "Zoe.Little@sohu.org.uk",
                            Name = "Mackenzie",
                            Surname = "Akhtar",
                            Title = "paypal.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4760)
                        },
                        new
                        {
                            Id = new Guid("021fddbe-1a37-47de-aaff-316ba8a63498"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4761),
                            DateOfBorn = new DateTime(1985, 3, 5, 1, 16, 22, 997, DateTimeKind.Unspecified).AddTicks(5366),
                            Email = "Genesis.Schofield@sky.co.uk",
                            Name = "Ashley",
                            Surname = "Naylor",
                            Title = "sohu.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4857)
                        },
                        new
                        {
                            Id = new Guid("024cef97-9f1a-4485-bfdf-58da6f54cd41"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4859),
                            DateOfBorn = new DateTime(1997, 7, 8, 21, 14, 12, 705, DateTimeKind.Unspecified).AddTicks(3355),
                            Email = "Sofia.Abbott@linkedin.org",
                            Name = "Jack",
                            Surname = "Lord",
                            Title = "stackoverflow.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4883)
                        },
                        new
                        {
                            Id = new Guid("72c9b907-6acb-4a57-8cf0-0d762e479f52"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4884),
                            DateOfBorn = new DateTime(1985, 7, 31, 12, 46, 32, 464, DateTimeKind.Unspecified).AddTicks(2158),
                            Email = "E.Green@maplin.info",
                            Name = "Jace",
                            Surname = "Sanders",
                            Title = "gmail.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4950)
                        },
                        new
                        {
                            Id = new Guid("0a25ae19-dcfe-4e70-8a46-7474dbd5f5ad"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4952),
                            DateOfBorn = new DateTime(2020, 5, 16, 13, 58, 0, 58, DateTimeKind.Unspecified).AddTicks(2706),
                            Email = "Mia.Whittaker@taobao.org.uk",
                            Name = "Dylan",
                            Surname = "Whitehead",
                            Title = "cnn.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4974)
                        },
                        new
                        {
                            Id = new Guid("05a18181-c640-470d-a09f-4a72ac40cbb4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(4975),
                            DateOfBorn = new DateTime(1987, 11, 26, 18, 23, 51, 398, DateTimeKind.Unspecified).AddTicks(2594),
                            Email = "E.Power@techcrunch.co.uk",
                            Name = "Anna",
                            Surname = "Williams",
                            Title = "flipkart.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5036)
                        },
                        new
                        {
                            Id = new Guid("80ae7fd5-cfdd-4c55-9e34-687beccedc04"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5037),
                            DateOfBorn = new DateTime(1976, 8, 3, 9, 42, 56, 690, DateTimeKind.Unspecified).AddTicks(5771),
                            Email = "W.Whelan@lego.biz",
                            Name = "Gianna",
                            Surname = "Wright",
                            Title = "wikipedia.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5060)
                        },
                        new
                        {
                            Id = new Guid("83370067-91a9-469c-a59f-82c7b2ffde5a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5061),
                            DateOfBorn = new DateTime(1980, 3, 1, 22, 54, 35, 338, DateTimeKind.Unspecified).AddTicks(7385),
                            Email = "Bailey.Fleming@sohu.net",
                            Name = "Harper",
                            Surname = "Adam",
                            Title = "baidu.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5124)
                        },
                        new
                        {
                            Id = new Guid("3a725ee6-0d3a-4528-be9c-863c1e7a152e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5126),
                            DateOfBorn = new DateTime(2015, 7, 20, 21, 11, 12, 615, DateTimeKind.Unspecified).AddTicks(828),
                            Email = "S.Wood@techcrunch.co.uk",
                            Name = "Ellie",
                            Surname = "Savage",
                            Title = "amazon.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5147)
                        },
                        new
                        {
                            Id = new Guid("ef7d7374-f98d-4aa7-8242-bc4346baf8ab"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5148),
                            DateOfBorn = new DateTime(1985, 2, 11, 7, 20, 5, 498, DateTimeKind.Unspecified).AddTicks(768),
                            Email = "Jeremiah.Whitehouse@adamriddick.com",
                            Name = "Kayden",
                            Surname = "Jones",
                            Title = "lego.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5212)
                        },
                        new
                        {
                            Id = new Guid("0972fbcc-e10e-4ef7-96fc-a385d8e1011d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5213),
                            DateOfBorn = new DateTime(1974, 5, 2, 4, 38, 58, 510, DateTimeKind.Unspecified).AddTicks(4064),
                            Email = "M.Jackson@expedia.co.uk",
                            Name = "Joseph",
                            Surname = "Wright",
                            Title = "bestbuy.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5235)
                        },
                        new
                        {
                            Id = new Guid("06f007bb-0791-4b0b-bcee-6b974815cb63"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5236),
                            DateOfBorn = new DateTime(2008, 7, 4, 12, 18, 16, 775, DateTimeKind.Unspecified).AddTicks(8932),
                            Email = "I.Nelson@163.us",
                            Name = "Jaxon",
                            Surname = "Boyd",
                            Title = "stackoverflow.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5340)
                        },
                        new
                        {
                            Id = new Guid("3be3d160-8549-49af-9cc8-71fd514d2f58"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5342),
                            DateOfBorn = new DateTime(2015, 2, 20, 12, 23, 26, 931, DateTimeKind.Unspecified).AddTicks(8550),
                            Email = "J.Robinson@etsy.biz",
                            Name = "Isabella",
                            Surname = "Riddick",
                            Title = "amazon.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5364)
                        },
                        new
                        {
                            Id = new Guid("73870f73-a044-40d4-a561-971b932b3a06"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5405),
                            DateOfBorn = new DateTime(2020, 5, 29, 13, 32, 54, 321, DateTimeKind.Unspecified).AddTicks(7516),
                            Email = "David.Barlow@yahoo.co",
                            Name = "Kimberly",
                            Surname = "Smith",
                            Title = "msdn.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5430)
                        },
                        new
                        {
                            Id = new Guid("2a0fbb62-e1f6-4bd4-bd64-fca1d1df8078"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5434),
                            DateOfBorn = new DateTime(1976, 7, 7, 18, 45, 38, 362, DateTimeKind.Unspecified).AddTicks(3164),
                            Email = "Adam.Hilton@163.co",
                            Name = "Mia",
                            Surname = "Roberts",
                            Title = "wikipedia.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5509)
                        },
                        new
                        {
                            Id = new Guid("a3c73c6d-0d55-4830-9216-0691d8beed31"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5511),
                            DateOfBorn = new DateTime(1981, 1, 17, 19, 38, 16, 361, DateTimeKind.Unspecified).AddTicks(5302),
                            Email = "B.Williams@bet365.org.uk",
                            Name = "Ryan",
                            Surname = "Hilton",
                            Title = "pinterest.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5534)
                        },
                        new
                        {
                            Id = new Guid("9524fe26-348d-4acc-be0b-ec7cad546e16"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5535),
                            DateOfBorn = new DateTime(1993, 4, 7, 12, 3, 18, 556, DateTimeKind.Unspecified).AddTicks(5384),
                            Email = "S.Roberts@etsy.co",
                            Name = "Nevaeh",
                            Surname = "Walters",
                            Title = "bing.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5597)
                        },
                        new
                        {
                            Id = new Guid("8694d6f4-5aeb-419f-9835-269b119f6ed0"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5598),
                            DateOfBorn = new DateTime(1976, 7, 9, 17, 54, 8, 644, DateTimeKind.Unspecified).AddTicks(4317),
                            Email = "Hailey.Fleming@etsy.info",
                            Name = "Alexander",
                            Surname = "Fleming",
                            Title = "yelp.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5620)
                        },
                        new
                        {
                            Id = new Guid("068ee288-1e35-45b9-a84f-7a4f1d39aa17"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5622),
                            DateOfBorn = new DateTime(1990, 1, 10, 20, 35, 4, 249, DateTimeKind.Unspecified).AddTicks(4470),
                            Email = "K.Boyd@expedia.co",
                            Name = "David",
                            Surname = "Riddick",
                            Title = "ebay.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5684)
                        },
                        new
                        {
                            Id = new Guid("06cd7a61-181d-45e9-b18e-7bb93fe6bfbb"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5685),
                            DateOfBorn = new DateTime(2017, 11, 25, 5, 24, 5, 797, DateTimeKind.Unspecified).AddTicks(6832),
                            Email = "L.Hancock@theguardian.org.uk",
                            Name = "Madelyn",
                            Surname = "Riddick",
                            Title = "wikia.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5711)
                        },
                        new
                        {
                            Id = new Guid("81018594-48f1-4f4c-84da-e5dfb520f27a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5712),
                            DateOfBorn = new DateTime(2018, 7, 23, 5, 18, 50, 489, DateTimeKind.Unspecified).AddTicks(6910),
                            Email = "G.Barlow@paypal.biz",
                            Name = "Aaliyah",
                            Surname = "Roberts",
                            Title = "arstechnica.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5775)
                        },
                        new
                        {
                            Id = new Guid("12f9517c-6305-477f-958d-532c149c0a0f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5776),
                            DateOfBorn = new DateTime(2017, 10, 28, 9, 58, 28, 853, DateTimeKind.Unspecified).AddTicks(256),
                            Email = "L.Baldwin@google.com",
                            Name = "Harper",
                            Surname = "Mohamed",
                            Title = "linkedin.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5798)
                        },
                        new
                        {
                            Id = new Guid("13447f1b-afd0-474a-b9bb-5e6379f37a2b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5799),
                            DateOfBorn = new DateTime(1979, 12, 22, 12, 12, 15, 778, DateTimeKind.Unspecified).AddTicks(5432),
                            Email = "Maya.Naylor@wikipedia.co",
                            Name = "Mason",
                            Surname = "Swift",
                            Title = "theguardian.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5860)
                        },
                        new
                        {
                            Id = new Guid("1a80d346-3eae-4c96-a3ac-cbc0bcc2e669"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5862),
                            DateOfBorn = new DateTime(1979, 12, 15, 13, 30, 51, 428, DateTimeKind.Unspecified).AddTicks(4421),
                            Email = "Jasmine.Mcfarlane@theguardian.org",
                            Name = "Ryder",
                            Surname = "Boyd",
                            Title = "flipkart.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5883)
                        },
                        new
                        {
                            Id = new Guid("b65f0233-b607-4d22-bec4-2c5fa20c117b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5884),
                            DateOfBorn = new DateTime(1980, 10, 8, 3, 39, 23, 724, DateTimeKind.Unspecified).AddTicks(5163),
                            Email = "J.Swift@linkedin.co",
                            Name = "Ayden",
                            Surname = "Carroll",
                            Title = "studio1337.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5946)
                        },
                        new
                        {
                            Id = new Guid("5f3eb81e-aec7-4668-baa3-bf3d94c7e083"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5947),
                            DateOfBorn = new DateTime(2001, 10, 12, 15, 58, 21, 152, DateTimeKind.Unspecified).AddTicks(1202),
                            Email = "C.Blair@bbc.info",
                            Name = "Paul",
                            Surname = "Weaver",
                            Title = "stackoverflow.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(5968)
                        },
                        new
                        {
                            Id = new Guid("0d122a07-c63b-4721-90a1-2f51fb986f86"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6008),
                            DateOfBorn = new DateTime(2006, 10, 15, 17, 48, 24, 980, DateTimeKind.Unspecified).AddTicks(9148),
                            Email = "Ellie.Stuart@sky.co.uk",
                            Name = "Natalie",
                            Surname = "Kenny",
                            Title = "stackoverflow.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            Id = new Guid("6c6044c8-1fbd-40cb-91a5-0179177f970f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6031),
                            DateOfBorn = new DateTime(1982, 8, 26, 9, 38, 51, 576, DateTimeKind.Unspecified).AddTicks(2301),
                            Email = "Serenity.Seymour@globo.com",
                            Name = "Bella",
                            Surname = "Giles",
                            Title = "cnn.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6093)
                        },
                        new
                        {
                            Id = new Guid("9397a401-1c23-40a6-80cd-04adb68812d2"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6095),
                            DateOfBorn = new DateTime(2012, 2, 3, 0, 10, 56, 917, DateTimeKind.Unspecified).AddTicks(5958),
                            Email = "Samuel.Barlow@wordpress.info",
                            Name = "Sophie",
                            Surname = "Riddick",
                            Title = "adamriddick.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6117)
                        },
                        new
                        {
                            Id = new Guid("45070723-2fc2-4777-90e1-0925e5f7dc93"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6118),
                            DateOfBorn = new DateTime(2004, 1, 10, 2, 1, 53, 776, DateTimeKind.Unspecified).AddTicks(334),
                            Email = "Jocelyn.Swift@techcrunch.info",
                            Name = "Tyler",
                            Surname = "Wright",
                            Title = "163.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6194)
                        },
                        new
                        {
                            Id = new Guid("a2c7c20d-675d-421a-9e90-6ef62e71f491"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6195),
                            DateOfBorn = new DateTime(1980, 10, 29, 12, 15, 51, 196, DateTimeKind.Unspecified).AddTicks(5173),
                            Email = "O.Silva@globo.org.uk",
                            Name = "Khloe",
                            Surname = "Green",
                            Title = "pinterest.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6218)
                        },
                        new
                        {
                            Id = new Guid("9295007c-6e7f-490f-9755-f727c2fcee22"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6219),
                            DateOfBorn = new DateTime(2019, 6, 17, 18, 2, 24, 986, DateTimeKind.Unspecified).AddTicks(4188),
                            Email = "A.Joyce@gmail.us",
                            Name = "Eli",
                            Surname = "Naylor",
                            Title = "ebay.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6281)
                        },
                        new
                        {
                            Id = new Guid("caf52e6b-1a87-477d-9d56-6f8a5f880d44"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6282),
                            DateOfBorn = new DateTime(1973, 3, 31, 22, 44, 4, 684, DateTimeKind.Unspecified).AddTicks(1776),
                            Email = "E.Kenny@paypal.org.uk",
                            Name = "Naomi",
                            Surname = "Watson",
                            Title = "pinterest.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6303)
                        },
                        new
                        {
                            Id = new Guid("91b96c8c-9bce-41fb-9837-9e0abf5f0b3f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6305),
                            DateOfBorn = new DateTime(1975, 6, 29, 20, 12, 49, 260, DateTimeKind.Unspecified).AddTicks(2199),
                            Email = "S.Walters@bing.org",
                            Name = "Savannah",
                            Surname = "Thornton",
                            Title = "amazon.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6361)
                        },
                        new
                        {
                            Id = new Guid("25addac4-fa1f-46b6-a5d6-6743c21ab224"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6362),
                            DateOfBorn = new DateTime(1991, 6, 19, 3, 33, 7, 674, DateTimeKind.Unspecified).AddTicks(7223),
                            Email = "C.Nash@linkedin.co",
                            Name = "Reagan",
                            Surname = "Briggs",
                            Title = "stackoverflow.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6384)
                        },
                        new
                        {
                            Id = new Guid("06e224c5-8899-4759-9905-185c15e76e77"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6385),
                            DateOfBorn = new DateTime(2002, 12, 19, 11, 45, 12, 587, DateTimeKind.Unspecified).AddTicks(6212),
                            Email = "L.Summers@expedia.net",
                            Name = "Scarlett",
                            Surname = "Nash",
                            Title = "ebay.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6476)
                        },
                        new
                        {
                            Id = new Guid("93e2c306-1585-406e-ab18-808868a58569"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6477),
                            DateOfBorn = new DateTime(1985, 11, 15, 19, 58, 4, 148, DateTimeKind.Unspecified).AddTicks(7654),
                            Email = "J.Giles@taobao.us",
                            Name = "Levi",
                            Surname = "Whitehouse",
                            Title = "lego.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6501)
                        },
                        new
                        {
                            Id = new Guid("58d16677-02ec-4132-8bf3-699b33fb8840"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6502),
                            DateOfBorn = new DateTime(2005, 8, 26, 16, 34, 35, 427, DateTimeKind.Unspecified).AddTicks(3118),
                            Email = "N.Watson@stackoverflow.net",
                            Name = "Savannah",
                            Surname = "Weaver",
                            Title = "sky.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6566)
                        },
                        new
                        {
                            Id = new Guid("5c107f5a-0dde-4441-b4e8-acec89c1520f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6567),
                            DateOfBorn = new DateTime(2009, 2, 23, 13, 44, 2, 961, DateTimeKind.Unspecified).AddTicks(6082),
                            Email = "Henry.Obrien@arstechnica.us",
                            Name = "Allison",
                            Surname = "Stuart",
                            Title = "expedia.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6589)
                        },
                        new
                        {
                            Id = new Guid("c26fba8e-8470-4d9c-af53-fb3b2a9e580d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6590),
                            DateOfBorn = new DateTime(2014, 11, 16, 6, 15, 43, 592, DateTimeKind.Unspecified).AddTicks(9320),
                            Email = "Oliver.Swift@bestbuy.net",
                            Name = "Adrian",
                            Surname = "Bradshaw",
                            Title = "stackoverflow.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6651)
                        },
                        new
                        {
                            Id = new Guid("41946809-ecc2-4196-b9e7-ed9c4bbc77c1"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6653),
                            DateOfBorn = new DateTime(1995, 10, 9, 15, 13, 45, 213, DateTimeKind.Unspecified).AddTicks(9611),
                            Email = "H.Harris@163.com",
                            Name = "Piper",
                            Surname = "Wilson",
                            Title = "deviantart.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6675)
                        },
                        new
                        {
                            Id = new Guid("eb371911-acf1-4620-9555-c99ee364006f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6676),
                            DateOfBorn = new DateTime(2001, 9, 17, 16, 23, 34, 823, DateTimeKind.Unspecified).AddTicks(2800),
                            Email = "Reagan.Briggs@qq.org",
                            Name = "Alex",
                            Surname = "Smith",
                            Title = "youtube.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6736)
                        },
                        new
                        {
                            Id = new Guid("3dbfd86d-3056-4a68-b056-2bb41747e0ab"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6738),
                            DateOfBorn = new DateTime(2002, 10, 25, 0, 53, 56, 682, DateTimeKind.Unspecified).AddTicks(2834),
                            Email = "M.Whitehouse@lego.com",
                            Name = "Riley",
                            Surname = "Chadwick",
                            Title = "yahoo.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6798)
                        },
                        new
                        {
                            Id = new Guid("da8c97ac-c6e6-4864-80b6-e5654b2fbc4b"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6800),
                            DateOfBorn = new DateTime(2002, 8, 7, 16, 11, 59, 963, DateTimeKind.Unspecified).AddTicks(1156),
                            Email = "L.Jackson@deviantart.co.uk",
                            Name = "Adam",
                            Surname = "Wood",
                            Title = "youtube.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6824)
                        },
                        new
                        {
                            Id = new Guid("0da85d4d-5fcc-4ca7-bb7b-624057011ed9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6825),
                            DateOfBorn = new DateTime(2015, 4, 19, 21, 32, 7, 710, DateTimeKind.Unspecified).AddTicks(9894),
                            Email = "Addison.Coles@studio1337.us",
                            Name = "Madeline",
                            Surname = "Jones",
                            Title = "pinterest.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6902)
                        },
                        new
                        {
                            Id = new Guid("e633bf43-0f4b-4f1d-9463-be71b0b735e3"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6903),
                            DateOfBorn = new DateTime(2009, 11, 18, 18, 32, 13, 97, DateTimeKind.Unspecified).AddTicks(7804),
                            Email = "L.Briggs@stackoverflow.biz",
                            Name = "Angel",
                            Surname = "Blair",
                            Title = "flipkart.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6926)
                        },
                        new
                        {
                            Id = new Guid("dcae0815-83b9-4825-9f90-a782f8e1dd65"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6929),
                            DateOfBorn = new DateTime(1978, 2, 19, 7, 50, 32, 159, DateTimeKind.Unspecified).AddTicks(7929),
                            Email = "Faith.Carroll@wordpress.com",
                            Name = "Molly",
                            Surname = "Silva",
                            Title = "cnn.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6991)
                        },
                        new
                        {
                            Id = new Guid("62ccf67a-665a-45f5-a859-4735a3db9e37"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(6993),
                            DateOfBorn = new DateTime(2009, 8, 7, 5, 6, 50, 453, DateTimeKind.Unspecified).AddTicks(3620),
                            Email = "M.Haines@paypal.com",
                            Name = "Ian",
                            Surname = "Briggs",
                            Title = "techcrunch.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7015)
                        },
                        new
                        {
                            Id = new Guid("b8923173-fabd-4cf9-a562-1167ce9ca97c"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7016),
                            DateOfBorn = new DateTime(2004, 6, 12, 14, 52, 18, 839, DateTimeKind.Unspecified).AddTicks(1622),
                            Email = "L.Riddick@msdn.biz",
                            Name = "Tristan",
                            Surname = "Sanders",
                            Title = "baidu.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7077)
                        },
                        new
                        {
                            Id = new Guid("7172a9ae-d1b2-4afe-a7ed-3f7f01d7c4eb"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7078),
                            DateOfBorn = new DateTime(1974, 3, 15, 8, 24, 30, 199, DateTimeKind.Unspecified).AddTicks(5635),
                            Email = "Elijah.Taylor@taobao.co.uk",
                            Name = "Ariana",
                            Surname = "Bradshaw",
                            Title = "sky.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7100)
                        },
                        new
                        {
                            Id = new Guid("8353162c-410c-4035-9e8e-d3f6c5f380db"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7101),
                            DateOfBorn = new DateTime(1979, 10, 8, 11, 58, 43, 78, DateTimeKind.Unspecified).AddTicks(1961),
                            Email = "C.Walker@qq.co.uk",
                            Name = "Evelyn",
                            Surname = "Wright",
                            Title = "pinterest.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7163)
                        },
                        new
                        {
                            Id = new Guid("b2cfee45-e91b-4b63-8d1d-612a61b434bc"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7164),
                            DateOfBorn = new DateTime(2000, 8, 15, 19, 9, 42, 370, DateTimeKind.Unspecified).AddTicks(3416),
                            Email = "E.Chadwick@gmail.org.uk",
                            Name = "Brandon",
                            Surname = "Barlow",
                            Title = "msdn.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7189)
                        },
                        new
                        {
                            Id = new Guid("d3dfe82b-595d-4b22-97cd-1f9e14d7d930"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7190),
                            DateOfBorn = new DateTime(2012, 10, 31, 6, 14, 49, 296, DateTimeKind.Unspecified).AddTicks(9360),
                            Email = "Lily.Sanders@deviantart.com",
                            Name = "Aaron",
                            Surname = "Blair",
                            Title = "arstechnica.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7251)
                        },
                        new
                        {
                            Id = new Guid("17269bc5-2a08-40f5-8c01-333c34fcb870"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7253),
                            DateOfBorn = new DateTime(2011, 11, 10, 15, 23, 34, 767, DateTimeKind.Unspecified).AddTicks(2792),
                            Email = "T.Taylor@theguardian.us",
                            Name = "Ariana",
                            Surname = "Buckley",
                            Title = "maplin.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7310)
                        },
                        new
                        {
                            Id = new Guid("599ba6e3-0870-4102-8a3e-4783aa1f3286"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7312),
                            DateOfBorn = new DateTime(1996, 5, 10, 11, 52, 52, 803, DateTimeKind.Unspecified).AddTicks(611),
                            Email = "Xavier.Boyd@163.co",
                            Name = "Nathan",
                            Surname = "Cullen",
                            Title = "youtube.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7334)
                        },
                        new
                        {
                            Id = new Guid("ff93eae9-6922-440b-981f-2bc473d1ac21"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7336),
                            DateOfBorn = new DateTime(2004, 3, 20, 18, 16, 19, 611, DateTimeKind.Unspecified).AddTicks(6296),
                            Email = "Alexa.Joyce@etsy.info",
                            Name = "Emily",
                            Surname = "Savage",
                            Title = "qq.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7392)
                        },
                        new
                        {
                            Id = new Guid("79ca66a3-2c6b-49fd-a3cc-d2c2ef4482d8"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7393),
                            DateOfBorn = new DateTime(2007, 4, 2, 14, 38, 30, 408, DateTimeKind.Unspecified).AddTicks(9516),
                            Email = "Levi.Mclean@arstechnica.co",
                            Name = "Blake",
                            Surname = "Roberts",
                            Title = "cnn.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7414)
                        },
                        new
                        {
                            Id = new Guid("e780c42a-f91f-4291-a34d-5b5de8a333e9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7416),
                            DateOfBorn = new DateTime(1989, 7, 14, 13, 17, 52, 823, DateTimeKind.Unspecified).AddTicks(3912),
                            Email = "M.Silva@yahoo.co.uk",
                            Name = "Emma",
                            Surname = "Williams",
                            Title = "expedia.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7505)
                        },
                        new
                        {
                            Id = new Guid("72773163-24c0-42a5-8f57-5a2570c32b26"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7507),
                            DateOfBorn = new DateTime(2019, 9, 5, 7, 38, 1, 230, DateTimeKind.Unspecified).AddTicks(8578),
                            Email = "Addison.Davies@lego.org.uk",
                            Name = "Lucas",
                            Surname = "Haines",
                            Title = "wikia.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            Id = new Guid("8a37e396-2952-42fe-b9dd-89ec7120cd9d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7531),
                            DateOfBorn = new DateTime(2012, 9, 8, 15, 17, 23, 613, DateTimeKind.Unspecified).AddTicks(9920),
                            Email = "Grace.Wright@163.org",
                            Name = "Emma",
                            Surname = "Barlow",
                            Title = "yahoo.org.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7614)
                        },
                        new
                        {
                            Id = new Guid("9e1e2483-a605-476c-87c2-83b83791354e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7616),
                            DateOfBorn = new DateTime(2005, 1, 29, 6, 25, 57, 50, DateTimeKind.Unspecified).AddTicks(296),
                            Email = "Brianna.Thompson@yelp.co",
                            Name = "Melanie",
                            Surname = "Power",
                            Title = "sohu.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7637)
                        },
                        new
                        {
                            Id = new Guid("13d776bc-6409-42bb-ae4d-06f9c4c1ac10"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7638),
                            DateOfBorn = new DateTime(1977, 1, 7, 5, 42, 17, 459, DateTimeKind.Unspecified).AddTicks(2140),
                            Email = "Jeremiah.Weaver@deviantart.net",
                            Name = "Skylar",
                            Surname = "Summers",
                            Title = "wikia.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            Id = new Guid("c46ba212-dac8-420f-9677-4d6f727cface"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7702),
                            DateOfBorn = new DateTime(1993, 2, 7, 4, 48, 55, 40, DateTimeKind.Unspecified).AddTicks(7675),
                            Email = "Joshua.Green@live.biz",
                            Name = "Carson",
                            Surname = "Burrows",
                            Title = "163.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7723)
                        },
                        new
                        {
                            Id = new Guid("eca998e3-2450-4388-ad61-68a5481a19e9"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7724),
                            DateOfBorn = new DateTime(1986, 3, 27, 15, 50, 34, 642, DateTimeKind.Unspecified).AddTicks(5641),
                            Email = "M.Robinson@163.org.uk",
                            Name = "Alexis",
                            Surname = "White",
                            Title = "live.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7787)
                        },
                        new
                        {
                            Id = new Guid("ccb46cca-1d63-49dc-a875-f290f9dba551"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7788),
                            DateOfBorn = new DateTime(1989, 8, 25, 5, 59, 33, 275, DateTimeKind.Unspecified).AddTicks(7719),
                            Email = "J.Harris@expedia.com",
                            Name = "Ava",
                            Surname = "Shepherd",
                            Title = "etsy.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7810)
                        },
                        new
                        {
                            Id = new Guid("5d191ecb-98ba-4d5f-81ef-229992716374"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7811),
                            DateOfBorn = new DateTime(1988, 9, 7, 23, 38, 34, 238, DateTimeKind.Unspecified).AddTicks(913),
                            Email = "C.Thompson@taobao.co",
                            Name = "Levi",
                            Surname = "Shepherd",
                            Title = "studio1337.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7872)
                        },
                        new
                        {
                            Id = new Guid("3b61aaa8-0917-410d-bedc-f5be3a4ad035"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7874),
                            DateOfBorn = new DateTime(1988, 7, 2, 8, 50, 4, 181, DateTimeKind.Unspecified).AddTicks(8465),
                            Email = "M.Leach@youtube.net",
                            Name = "Nolan",
                            Surname = "Giles",
                            Title = "sohu.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7895)
                        },
                        new
                        {
                            Id = new Guid("9e8be155-f5c9-42b3-9217-34d82cd1b77e"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7897),
                            DateOfBorn = new DateTime(1980, 12, 4, 5, 27, 40, 662, DateTimeKind.Unspecified).AddTicks(5826),
                            Email = "Genesis.Little@163.org",
                            Name = "Madelyn",
                            Surname = "Dale",
                            Title = "arstechnica.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7958)
                        },
                        new
                        {
                            Id = new Guid("14701d19-fe10-4df2-a1a8-121afc4357ed"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7960),
                            DateOfBorn = new DateTime(2003, 4, 12, 19, 14, 58, 536, DateTimeKind.Unspecified).AddTicks(8238),
                            Email = "E.Williams@cnn.biz",
                            Name = "Lucas",
                            Surname = "Vaughan",
                            Title = "amazon.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7982)
                        },
                        new
                        {
                            Id = new Guid("02d7fae6-c9e6-4643-a0f4-17bd7debc9a4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(7983),
                            DateOfBorn = new DateTime(1991, 8, 3, 10, 45, 10, 176, DateTimeKind.Unspecified).AddTicks(7684),
                            Email = "Isaac.Sanders@live.com",
                            Name = "Ella",
                            Surname = "Stuart",
                            Title = "studio1337.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8041)
                        },
                        new
                        {
                            Id = new Guid("259f3a2b-1010-4385-8c83-ff82e1c55ad4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8042),
                            DateOfBorn = new DateTime(1997, 7, 4, 11, 55, 0, 286, DateTimeKind.Unspecified).AddTicks(2969),
                            Email = "Caroline.Osborne@deviantart.biz",
                            Name = "Parker",
                            Surname = "Savage",
                            Title = "wordpress.co.uk",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8100)
                        },
                        new
                        {
                            Id = new Guid("76d3161f-20f8-44b9-a263-72575339ad1d"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8101),
                            DateOfBorn = new DateTime(1974, 3, 1, 14, 1, 2, 808, DateTimeKind.Unspecified).AddTicks(7754),
                            Email = "L.Briggs@taobao.us",
                            Name = "Harper",
                            Surname = "Whelan",
                            Title = "google.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8126)
                        },
                        new
                        {
                            Id = new Guid("7785ac66-5a6e-4f9a-9f5c-9b2750c331e8"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8127),
                            DateOfBorn = new DateTime(2004, 1, 12, 21, 50, 31, 483, DateTimeKind.Unspecified).AddTicks(582),
                            Email = "P.Barlow@stackoverflow.com",
                            Name = "Evelyn",
                            Surname = "Jackson",
                            Title = "wikia.net",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8188)
                        },
                        new
                        {
                            Id = new Guid("9134d92b-c3a3-4204-95ac-19cf2ea7a8e7"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8189),
                            DateOfBorn = new DateTime(1985, 2, 23, 23, 17, 9, 290, DateTimeKind.Unspecified).AddTicks(4032),
                            Email = "D.Haines@deviantart.info",
                            Name = "Morgan",
                            Surname = "Williams",
                            Title = "theguardian.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8212)
                        },
                        new
                        {
                            Id = new Guid("f131937f-a51d-4f2b-8819-e70cc3e8b67a"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8213),
                            DateOfBorn = new DateTime(1991, 9, 26, 12, 15, 36, 308, DateTimeKind.Unspecified).AddTicks(1875),
                            Email = "A.Lewis@maplin.info",
                            Name = "Sarah",
                            Surname = "Mclean",
                            Title = "amazon.info",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8287)
                        },
                        new
                        {
                            Id = new Guid("f8818e46-8438-4460-b0c7-f7634ca6f25f"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8289),
                            DateOfBorn = new DateTime(2004, 3, 12, 3, 48, 51, 554, DateTimeKind.Unspecified).AddTicks(2860),
                            Email = "Adrian.Power@wikia.net",
                            Name = "Carson",
                            Surname = "Giles",
                            Title = "arstechnica.us",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8314)
                        },
                        new
                        {
                            Id = new Guid("916fbf0c-8c38-4a36-8b36-0b2e14f39680"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8315),
                            DateOfBorn = new DateTime(1976, 7, 10, 4, 21, 29, 878, DateTimeKind.Unspecified).AddTicks(5390),
                            Email = "Chloe.Jackson@cnn.net",
                            Name = "Gabriel",
                            Surname = "Riddick",
                            Title = "ebay.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8374)
                        },
                        new
                        {
                            Id = new Guid("2e88e74d-0070-43b7-a95b-8ba4149f1d42"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8376),
                            DateOfBorn = new DateTime(1981, 9, 3, 22, 9, 31, 754, DateTimeKind.Unspecified).AddTicks(3296),
                            Email = "M.Briggs@bestbuy.biz",
                            Name = "Daniel",
                            Surname = "Thomas",
                            Title = "microsoft.com",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8398)
                        },
                        new
                        {
                            Id = new Guid("60315e96-a7cd-44ee-bf4b-fa047ad0f4b5"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8399),
                            DateOfBorn = new DateTime(2008, 1, 9, 10, 20, 12, 483, DateTimeKind.Unspecified).AddTicks(8922),
                            Email = "Elizabeth.Whittaker@bing.net",
                            Name = "Amelia",
                            Surname = "Boyd",
                            Title = "msdn.org",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8459)
                        },
                        new
                        {
                            Id = new Guid("808c484b-54d2-4520-b076-0cbf7df106b4"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8460),
                            DateOfBorn = new DateTime(2016, 9, 29, 16, 40, 54, 295, DateTimeKind.Unspecified).AddTicks(6970),
                            Email = "Z.Little@ask.biz",
                            Name = "Nolan",
                            Surname = "Wood",
                            Title = "deviantart.co",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8483)
                        },
                        new
                        {
                            Id = new Guid("d8f904dc-cc73-4711-abf8-617d0106a118"),
                            AddedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8484),
                            DateOfBorn = new DateTime(1980, 10, 22, 11, 46, 7, 242, DateTimeKind.Unspecified).AddTicks(5945),
                            Email = "A.Evans@arstechnica.biz",
                            Name = "Parker",
                            Surname = "Wilson",
                            Title = "paypal.biz",
                            UpdatedDate = new DateTime(2020, 11, 20, 14, 3, 18, 61, DateTimeKind.Local).AddTicks(8574)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
